Methods are described in detail in the Statistical Analysis Plan which can be viewed [online](https://www.overleaf.com/read/ffzknqdcjkpw).  Once the page has loaded click on PDF at the top of the page to download a PDF copy.  Briefly though the study seeks to investigate via interuptted time-series analysis whether closing Accident and Emergency departments impacts on any of a host of pre-selected indicators of the quality of health care provision[@knotopantelis2015;@penfold2013].  [Prais-Winsten regression](https://en.wikipedia.org/wiki/Prais%E2%80%93Winsten_estimation)[@prais1954] is utilised to account for auto-correlation between sequential measurements over time.  Broadly the approach taken is that of @turner2013.

### Models

Seven models are tested sequentially with growing complexity and are detailed below.

Table: Models tested in ClosED

Model | Case Site  | Control Site     | Panel | Covariates
------|------------|------------------|-------|----------------------------------------
1     | Individual | None             | ED    | season + time + closure + steps
2     | Individual | One Matched      | ED    | season + time + closure * site + steps
3     | Individual | All Matched      | ED    | season + time + closure * site + steps
4     | All        | One Matched      | ED    | season + time + closure * site + steps
5     | All        | All Matched      | ED    | season + time + closure * site + steps
6     | Individual | One Matched      | LSOA  | season + time + closure * site + steps + change in ED time
7     | All        | All Matched      | LSOA  | season + time + closure * site + steps + change in ED time

### Panels

The panels that are being considered change depending on the type of analyses that are being performed (see above table).  If the summary data across a catchment area is being analysed under the 'step' models then the panels are the Trust/Hospital/Emergency Departments themselves.  If the data is being considered at the Lower Super Output Area (LSOA) as it is under the 'dose' models which include a 'change in ED time' term then the panels are the LSOAs themselves, since these are the units on which repeated measures over time are available and are being analysed.



### Steps

The closure of ED departments is modelled using a dummy variable (coded 0 for closed and 1 for open) to indicate whether the ED department is open/closed for any given month in a given hospital.  However, other factors might influence attendance and documentary analysis was undertaken at the case sites (where EDs closed) and one matched control for each case site to identify additional events that might impact on the indicators being considered.  These are detailed in full in [this spreadhsheet](https://goo.gl/TlhfCF) and  of the different steps identified they have been categorised into the introduction of the NHS111 Helpline (`nhs111`), other medical care centres opening (`other.centre`) and the diversion of ambulances (`ambulance.divert`) and are summarised in the table below for the ten hospitals.

Table: Steps used in the model. Dates indicate the month of event (relative month is shown in brackets).

Hospital         | ED closure      | NHS 111         | Other Centre    | Ambulance Diversion
-----------------|-----------------|-----------------|-----------------|---------------------
Bishop Auckland  | 2009-10-01 (25) | 2010-08-01 (35) |                 |
Whitehaven       |                 |                 |                 |
Hartlepool       | 2011-08-01 (25) | 2013-04-01 (45) | 2011-05-01 (22) |
Grimsby          |                 | 2010-11-01 (16) |                 |
Hemel Hempstead  | 2009-03-01 (25) |                 | 2008-10-01 (20) |
Warwick          |                 |                 |                 |
Newark           | 2011-04-01 (25) |                 |                 |
Southport        |                 | 2013-03-01 (48) | 2009-06-01 (03) |
Rochdale         | 2011-04-01 (25) | 2013-03-01 (48) |                 | 2010-08-01 (17)
Rotherham        |                 | 2013-03-01 (48) | 2009-06-01 (11) |


### Spurious Data Points

Time-series plots of the raw data were first inspected to identify any potentially spurious data points.  Where such data points were considered to be erroneous they were removed from the panel in which they pertain to and in all subsequent analyses they were also removed from the corresponding sites that were included in the analyses so that the panels remained balanced.

### Heteroskedasticity and Correlation

Currently panel-corrected standard errors are used which are robust to heteroskedaasticity and contemporaneous correlation across panels, but other options are available, such as a Huber-White style sandwich estimateor for panel heteroskedasticity, panel weighted least squares procedure for heteroskedasticity or Parks-Kmenta FGLS to estimate both heteroskedasticity and correlation.  For full details see [Details under PanelAR](http://www.rdocumentation.org/packages/panelAR/functions/panelAR).


### Software

This work is being undertaken using the Free Open Source Software (FOSS) [R](https://www.r-project.org/).  Work is undertaken in a reproducible framework using [R Markdown](http://rmarkdown.rstudio.com/) meaning the results you see in this document (tables, graphs, regression output etc.) are generated dynamically.

<!--- Run all analyses --->
```{r child = 'subsections/analysis.Rmd', eval = TRUE}
