<!--- Additiona avoidable admissions and avoidable deaths that could be requested --->
<!--- Avoidable Emergency Admissions - Acute Mental Health Crisis --->
```{r avoidable_emergency_admissions_acute_mental_health_crisis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.acute.mental.health.crisis <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'acute mental health crisis',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
<!--- Avoidable Emergency Admissions - Angina --->
```{r avoidable_emergency_admissions_angina, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.angina <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'angina',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Blocked Catheter --->
```{r avoidable_emergency_admissions_blocked_catheter, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.blocked.catheter <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'blocked catheter',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Cellulitis --->
```{r avoidable_emergency_admissions_cellulitis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.cellulitis <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'cellulitis',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Copd --->
```{r avoidable_emergency_admissions_copd, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.copd <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'copd',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Dvt --->
```{r avoidable_emergency_admissions_dvt, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.dvt <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'dvt',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Epileptic Fit --->
```{r avoidable_emergency_admissions_epileptic_fit, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.epileptic.fit <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'epileptic fit',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Falls --->
```{r avoidable_emergency_admissions_falls, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.falls <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'falls (75+ years)',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Hypoglycaemia --->
```{r avoidable_emergency_admissions_hypoglycaemia, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.hypoglycaemia <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'hypoglycaemia',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Minor Head Injuries --->
```{r avoidable_emergency_admissions_minor_head_injuries, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.minor.head.injuries <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'minor head injuries',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Pyrexial Child --->
```{r avoidable_emergency_admissions_pyrexial_child, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.pyrexial.child <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'pyrexial child (<6 years)',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Urinary Tract Infection --->
```{r avoidable_emergency_admissions_urinary_tract_infection, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.urinary.tract.infection <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'urinary tract infection',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Anaphylaxis --->
```{r case_fatality_ratio_anaphylaxis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.anaphylaxis <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'anaphylaxis',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Asphyxiation --->
```{r case_fatality_ratio_asphyxiation, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.asphyxiation <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'asphyxiation',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Asthma --->
```{r case_fatality_ratio_asthma, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.asthma <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'asthma',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Falls --->
```{r case_fatality_ratio_falls, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.falls <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'falls',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Fractured Neck Of Femur --->
```{r case_fatality_ratio_fractured_neck_of_femur, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.fractured.neck.of.femur <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'fractured neck of femur',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Meningitis --->
```{r case_fatality_ratio_meningitis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.meningitis <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'meningitis',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Myocardial Infarction --->
```{r case_fatality_ratio_myocardial_infarction, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.myocardial.infarction <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'myocardial infarction',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Pregnancy And Birth Related --->
```{r case_fatality_ratio_pregnancy_and_birth_related, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.pregnancy.and.birth.related <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'pregnancy and birth related',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Road Traffic Accident --->
```{r case_fatality_ratio_road_traffic_accident, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.road.traffic.accident <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'road traffic accident',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Ruptured Aortic Aneurysm --->
```{r case_fatality_ratio_ruptured_aortic_aneurysm, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.ruptured.aortic.aneurysm <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'ruptured aortic aneurysm',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Self Harm --->
```{r case_fatality_ratio_self.harm, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.self.harm <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'self harm',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Septic Shock --->
```{r case_fatality_ratio_septic_shock, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.septic.shock <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'septic shock',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Serious Head Injury --->
```{r case_fatality_ratio_serious_head_injury, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.serious.head.injury <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'serious head injury',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model6.1         = model.opts$mod6.1,
                                     model6.2         = model.opts$mod6.2,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
