<!--- Runs all analyses, saving results as an R object for loading --->
<!--- Summary --->
```{r load_data, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
## Obtain the OS and node such that the data can be conditionally loaded
os <- .Platform$OS.type
node <- Sys.info()[['nodename']]
if(os != 'unix'){
    load('d:/Rpackages/rclosed/data/ed attendances by mode measure - lsoa - 2016-05-24 14.25.Rda')
    load('d:/Rpackages/rclosed/data/ed attendances by mode measure - site - 2016-05-24 14.26.Rda')
    load('d:/Rpackages/rclosed/data/unnecessary ed attendances measure - lsoa - 2016-05-24 14.26.Rda')
    load('d:/Rpackages/rclosed/data/unnecessary ed attendances measure - site - 2016-05-24 14.26.Rda')
    load('d:/Rpackages/rclosed/data/ed attendances admitted measure - lsoa - 2016-05-24 14.28.Rda')
    load('d:/Rpackages/rclosed/data/ed attendances admitted measure - site - 2016-05-24 14.28.Rda')
    load('d:/Rpackages/rclosed/data/emergency admissions measure - lsoa - 2016-05-24 14.30.Rda')
    load('d:/Rpackages/rclosed/data/emergency admissions measure - site - 2016-05-24 14.31.Rda')
##    load('d:/Rpackages/rclosed/data/critical care stays measure - lsoa - 2016-05-24 14.32.Rda')
##    load('d:/Rpackages/rclosed/data/critical care stays measure - site - 2016-05-24 14.32.Rda')
    load('d:/Rpackages/rclosed/data/critical care stays measure - lsoa - 2016-06-10 18.17.Rda')
    load('d:/Rpackages/rclosed/data/critical care stays measure - site - 2016-06-10 18.18.Rda')
    load('d:/Rpackages/rclosed/data/length of stay measure - lsoa - 2016-05-24 14.34.Rda')
    load('d:/Rpackages/rclosed/data/length of stay measure - site - 2016-05-24 14.35.Rda')
    load('d:/Rpackages/rclosed/data/ambulance mean times measure - lsoa - 2016-06-17 01.21.Rda')
    load('d:/Rpackages/rclosed/data/ambulance mean times measure - site - 2016-06-17 01.23.Rda')
    load('d:/Rpackages/rclosed/data/case fatality measure - lsoa - 2016-06-10 18.09.Rda')
    load('d:/Rpackages/rclosed/data/case fatality measure - site - 2016-06-10 18.10.Rda')
} else if(os == 'unix' & node == 'mcru-closed-hp.shef.ac.uk'){
    load('~/work/closed/lib/data/ed attendances by mode measure - lsoa - 2016-05-24 14.25.Rda')
    load('~/work/closed/lib/data/ed attendances by mode measure - site - 2016-05-24 14.26.Rda')
    load('~/work/closed/lib/data/unnecessary ed attendances measure - lsoa - 2016-05-24 14.26.Rda')
    load('~/work/closed/lib/data/unnecessary ed attendances measure - site - 2016-05-24 14.26.Rda')
    load('~/work/closed/lib/data/ed attendances admitted measure - lsoa - 2016-05-24 14.28.Rda')
    load('~/work/closed/lib/data/ed attendances admitted measure - site - 2016-05-24 14.28.Rda')
    load('~/work/closed/lib/data/emergency admissions measure - lsoa - 2016-05-24 14.30.Rda')
    load('~/work/closed/lib/data/emergency admissions measure - site - 2016-05-24 14.31.Rda')
    ## load('~/work/closed/lib/data/critical care stays measure - lsoa - 2016-05-24 14.32.Rda')
    ## load('~/work/closed/lib/data/critical care stays measure - site - 2016-05-24 14.32.Rda')
    load('~/work/closed/lib/data/critical care stays measure - lsoa - 2016-06-10 18.17.Rda')
    load('~/work/closed/lib/data/critical care stays measure - site - 2016-06-10 18.18.Rda')
    load('~/work/closed/lib/data/length of stay measure - lsoa - 2016-05-24 14.34.Rda')
    load('~/work/closed/lib/data/length of stay measure - site - 2016-05-24 14.35.Rda')
    load('~/work/closed/lib/data/ambulance mean times measure - lsoa - 2016-06-17 01.21.Rda')
    load('~/work/closed/lib/data/ambulance mean times measure - site - 2016-06-17 01.23.Rda')
    load('~/work/closed/lib/data/ambulance non-conveyance measure - lsoa - 2016-07-15 20.09.Rda')
    load('~/work/closed/lib/data/ambulance non-conveyance measure - site - 2016-07-15 20.09.Rda')
    load('~/work/closed/lib/data/ambulance red calls measure - lsoa - 2016-07-15 20.11.Rda')
    load('~/work/closed/lib/data/ambulance red calls measure - site - 2016-07-15 20.11.Rda')
    ## load('~/work/closed/lib/data/case fatality measure - lsoa - 2016-06-10 18.09.Rda')
    ## load('~/work/closed/lib/data/case fatality measure - site - 2016-06-10 18.10.Rda')
    load('~/work/closed/lib/data/case fatality measure - lsoa - 2016-07-15 21.05.Rda')
    load('~/work/closed/lib/data/case fatality measure - site - 2016-07-15 21.06.Rda')
}
## Tidy data frames, why I didn't do this first I've no idea!
ed_attendances_by_mode_measure          <- closed_tidy(ed_attendances_by_mode_measure)
ed_attendances_by_mode_site_measure     <- closed_tidy(ed_attendances_by_mode_site_measure)
unnecessary_ed_attendances_measure      <- closed_tidy(unnecessary_ed_attendances_measure)
unnecessary_ed_attendances_site_measure <- closed_tidy(unnecessary_ed_attendances_site_measure)
ed_attendances_admitted_measure         <- closed_tidy(ed_attendances_admitted_measure)
ed_attendances_admitted_site_measure    <- closed_tidy(ed_attendances_admitted_site_measure)
critical_care_cips_measure              <- closed_tidy(critical_care_cips_measure)
critical_care_cips_site_measure         <- closed_tidy(critical_care_cips_site_measure)
emergency_admissions_measure            <- closed_tidy(emergency_admissions_measure)
emergency_admissions_site_measure       <- closed_tidy(emergency_admissions_site_measure)
length_of_stay_measure                  <- closed_tidy(length_of_stay_measure)
length_of_stay_site_measure             <- closed_tidy(length_of_stay_site_measure)
amb_mean_times_measure                  <- closed_tidy(amb_mean_times_measure)
amb_mean_times_site_measure             <- closed_tidy(amb_mean_times_site_measure)
amb_non_conveyance_measure              <- closed_tidy(amb_non_conveyance_measure)
amb_non_conveyance_site_measure         <- closed_tidy(amb_non_conveyance_site_measure)
amb_red_calls_measure                   <- closed_tidy(amb_red_calls_measure)
amb_red_calls_site_measure              <- closed_tidy(amb_red_calls_site_measure)

```

```{r define_models, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
## Set model options here (easier when tweaking en-mass)
model.opts <- list()
model.opts
model.opts$mod1  <- c('closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod2  <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod3a <- c('pooled.control * closure', 'town', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod4  <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod5  <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod6  <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert', 'diff.time.to.ed')
if(os != 'unix' | node != 'mcru-closed-hp.shef.ac.uk'){
    model.opts$mod7 = NULL
} else{
    model.opts$mod7 <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert', 'diff.time.to.ed')
}
model.opts$mod3b <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$panel.lsoa		<- 'lsoa'
model.opts$panel.trust		<- 'town'
model.opts$timevar		<- 'relative.month'
model.opts$outcome		<- 'value'
model.opts$autocorr		<- 'ar1'
model.opts$panelcorrmethod	<- 'pcse'
model.opts$coefficients		<- 'closure.town'
model.opts$seq.times		<- FALSE
model.opts$plot			<- TRUE
model.opts$common.y		<- TRUE
model.opts$theme		<- theme_bw()
model.opts$return.df		<- FALSE
model.opts$return.model		<- TRUE
model.opts$return.residuals	<- FALSE
model.opts$join.line            <- FALSE
model.opts$legend               <- TRUE
model.opts$rho.na.rm            <- TRUE
## Other Common options
systematic.outlier <- 3
## Regularly want to exclude majority of 'avoidable emergency admission' and 'case fatality ratio'
## sub indicators so put them in lists here to (hopefully) save a lot of retyping
exclude.avoidable <- c('acute mental health crisis',
                       'angina',
                       'blocked catheter',
                       'cellulitis',
                       'copd',
                       'dvt',
                       'epileptic fit',
                       'falls (75+ years)',
                       'hypoglycaemia',
                       'minor head injuries',
                       'pyrexial child (<6 years)',
                       'urinary tract infection')
exclude.fatality  <- c('anaphylaxis',
                       'asphyxiation',
                       'asthma',
                       'falls',
                       'fractured neck of femur',
                       'meningitis',
                       'myocardial infarction',
                       'pregnancy and birth related',
                       'road traffic accident',
                       'ruptured aortic aneurysm',
                       'self harm',
                       'septic shock',
                       'serious head injury')

```

```{r summary_analysis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
## Summarise differences in time to ED
diff.time.to.ed <- closed_summary(df          = ed_attendances_by_mode_measure,
                             df.steps    = sites,
                             vars        = value,
                             digits      = 3,
                             latex       = FALSE,
                             html        = FALSE)
## Simple summary of the missing data across datasets
check.ed.attendances <- closed_missing_summary(df.lsoa = ed_attendances_by_mode_measure,
                                               df.site = ed_attendances_by_mode_site_measure)
check.ed.unnecessary <- closed_missing_summary(df.lsoa = unnecessary_ed_attendances_measure,
                                               df.site = unnecessary_ed_attendances_site_measure)
check.ed.admitted    <- closed_missing_summary(df.lsoa = ed_attendances_admitted_measure,
                                               df.site = ed_attendances_admitted_site_measure)
check.critical.care  <- closed_missing_summary(df.lsoa = critical_care_cips_measure,
                                               df.site = critical_care_cips_site_measure)
check.length.stay    <- closed_missing_summary(df.lsoa = length_of_stay_measure,
                                               df.site = length_of_stay_site_measure)
## Bind into two data frames for tabulating
check.length.stay$check.lsoa$sub.measure[is.na(check.length.stay$check.lsoa$sub.measure)] <- "N/A"
check.lsoa <- rbind(check.ed.attendances$check.lsoa,
                    check.ed.unnecessary$.lsoa,
                    check.ed.admitted$check.lsoa,
                    check.critical.care$check.lsoa,
                    check.length.stay$check.lsoa) %>%
              ungroup() %>%
              arrange(measure, sub.measure, relative.month, group, town) %>%
	      dplyr::select(measure, sub.measure, town, relative.month, n)
names(check.lsoa) <- c('Measure', 'Sub-Measure', 'Town', 'Relative Month', 'LSOAs')

check.length.stay$check.site$sub.measure[is.na(check.length.stay$check.site$sub.measure)] <- "N/A"
check.site <- rbind(check.ed.attendances$check.site,
                    check.ed.unnecessary$.site,
                    check.ed.admitted$check.site,
                    check.critical.care$check.site,
                    check.length.stay$check.site) %>%
              arrange(measure, sub.measure, relative.month, group, town) %>%
	      dplyr::select(measure, sub.measure, town, relative.month)
names(check.site) <- c('Measure', 'Sub-Measure', 'Town', 'Relative Month')
```
<!--- Mode of Arrival - Any --->
```{r mode_of_arrival_any, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
mode.of.arrival.any <- closed_models(df.lsoa          = ed_attendances_by_mode_measure,
                                     df.trust         = ed_attendances_by_mode_site_measure,
                                     indicator        = 'ed attendances',
                                     sub.indicator    = 'any',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     ## return.df        = model.opts$return.df,
                                     return.df        = TRUE,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
<!--- Mode of Arrival - Other --->
```{r mode_of_arrival_other, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
mode.of.arrival.other <- closed_models(df.lsoa         = ed_attendances_by_mode_measure,
                                     df.trust         = ed_attendances_by_mode_site_measure,
                                     indicator        = 'ed attendances',
                                     sub.indicator    = 'other',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Mode of Arrival - Ambulance --->
```{r mode_of_arrival_ambulance, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
mode.of.arrival.ambulance <- closed_models(df.lsoa         = ed_attendances_by_mode_measure,
                                     df.trust         = ed_attendances_by_mode_site_measure,
                                     indicator        = 'ed attendances',
                                     sub.indicator    = 'ambulance',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Unnecessary Attendance - NA --->
```{r unnecessary_ed_attendances, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
unnecessary.attendance <- closed_models(df.lsoa         = unnecessary_ed_attendances_measure,
                                     df.trust         = unnecessary_ed_attendances_site_measure,
                                     indicator        = 'unnecessary ed attendances',
                                     sub.indicator    = 'all',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
<!--- All Emergency Admissions - All --->
```{r all_emergency_admissions_all, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
all.emergency.admissions.all <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'all emergency admissions',
                                     sub.indicator    = 'all',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Any --->
```{r avoidable_emergency_admissions_all, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.any <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'any',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Acute Mental Health Crisis --->
```{r avoidable_emergency_admissions_acute_mental_health_crisis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.acute.mental.health.crisis <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'acute mental health crisis',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
<!--- Avoidable Emergency Admissions - Angina --->
```{r avoidable_emergency_admissions_angina, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.angina <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'angina',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Blocked Catheter --->
```{r avoidable_emergency_admissions_blocked_catheter, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.blocked.catheter <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'blocked catheter',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Cellulitis --->
```{r avoidable_emergency_admissions_cellulitis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.cellulitis <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'cellulitis',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Copd --->
```{r avoidable_emergency_admissions_copd, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.copd <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'copd',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Dvt --->
```{r avoidable_emergency_admissions_dvt, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.dvt <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'dvt',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Epileptic Fit --->
```{r avoidable_emergency_admissions_epileptic_fit, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.epileptic.fit <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'epileptic fit',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Falls --->
```{r avoidable_emergency_admissions_falls, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.falls <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'falls (75+ years)',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Hypoglycaemia --->
```{r avoidable_emergency_admissions_hypoglycaemia, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.hypoglycaemia <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'hypoglycaemia',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Minor Head Injuries --->
```{r avoidable_emergency_admissions_minor_head_injuries, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.minor.head.injuries <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'minor head injuries',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Chest Pain --->
```{r avoidable_emergency_admissions_chest_pain, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.chest.pain <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'non-specific chest pain',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Pyrexial Child --->
```{r avoidable_emergency_admissions_pyrexial_child, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.pyrexial.child <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'pyrexial child (<6 years)',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Avoidable Emergency Admissions - Urinary Tract Infection --->
```{r avoidable_emergency_admissions_urinary_tract_infection, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
avoidable.emergency.admissions.urinary.tract.infection <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'avoidable emergency admissions',
                                     sub.indicator    = 'urinary tract infection',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- ED Attendances Admitted - All --->
```{r ed_attendances_admitted_all, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ed.attendances.admitted.all <- closed_models(df.lsoa         = ed_attendances_admitted_measure,
                                     df.trust         = ed_attendances_admitted_site_measure,
                                     indicator        = 'ed attendances admitted',
                                     sub.indicator    = 'all',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- ED Attendances Admitted - Fraction Admitted --->
```{r ed_attendances_admitted_fraction_admitted, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ed.attendances.admitted.fraction.admitted <- closed_models(df.lsoa         = ed_attendances_admitted_measure,
                                     df.trust         = ed_attendances_admitted_site_measure,
                                     indicator        = 'ed attendances admitted',
                                     sub.indicator    = 'fraction admitted',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- ED Attendances Admitted - Admitted --->
```{r ed_attendances_admitted_admitted, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ed.attendances.admitted.admitted <- closed_models(df.lsoa         = ed_attendances_admitted_measure,
                                     df.trust         = ed_attendances_admitted_site_measure,
                                     indicator        = 'ed attendances admitted',
                                     sub.indicator    = 'admitted',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Critical Care - All --->
```{r critical_care_cips_all, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
critical.care.cips.all <- closed_models(df.lsoa         = critical_care_cips_measure,
                                     df.trust         = critical_care_cips_site_measure,
                                     indicator        = 'critical care stays',
                                     sub.indicator    = 'all',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Critical Care - Critical --->
```{r critical_care_cips_critical, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
critical.care.cips.critical <- closed_models(df.lsoa         = critical_care_cips_measure,
                                     df.trust         = critical_care_cips_site_measure,
                                     indicator        = 'critical care stays',
                                     sub.indicator    = 'critical care',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Critical Care - Fraction --->
```{r critical_care_cips_fraction, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
critical.care.cips.fraction <- closed_models(df.lsoa         = critical_care_cips_measure,
                                     df.trust         = critical_care_cips_site_measure,
                                     indicator        = 'critical care stays',
                                     sub.indicator    = 'fraction critical care',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Length of Stay - Mean --->
```{r length_of_stay_mean, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
length.of.stay.mean <- closed_models(df.lsoa         = length_of_stay_measure,
                                     df.trust         = length_of_stay_site_measure,
                                     indicator        = 'length of stay',
                                     sub.indicator    = 'mean',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Length of Stay - Median --->
```{r length_of_stay_median, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
length.of.stay.median <- closed_models(df.lsoa         = length_of_stay_measure,
                                     df.trust         = length_of_stay_site_measure,
                                     indicator        = 'length of stay',
                                     sub.indicator    = 'median',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
<!--- Case Fatality Ratio - Any --->
```{r case_fatality_ratio_any, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.any <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'any',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
<!--- Case Fatality Ratio - Acute Heart Failure --->
```{r case_fatality_ratio_acute_heart_failure, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.acute.heart.failure <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'acute heart failure',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Anaphylaxis --->
```{r case_fatality_ratio_anaphylaxis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.anaphylaxis <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'anaphylaxis',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Asphyxiation --->
```{r case_fatality_ratio_asphyxiation, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.asphyxiation <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'asphyxiation',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Asthma --->
```{r case_fatality_ratio_asthma, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.asthma <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'asthma',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Falls --->
```{r case_fatality_ratio_falls, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.falls <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'falls',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Fractured Neck Of Femur --->
```{r case_fatality_ratio_fractured_neck_of_femur, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.fractured.neck.of.femur <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'fractured neck of femur',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Meningitis --->
```{r case_fatality_ratio_meningitis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.meningitis <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'meningitis',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Myocardial Infarction --->
```{r case_fatality_ratio_myocardial_infarction, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.myocardial.infarction <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'myocardial infarction',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Pregnancy And Birth Related --->
```{r case_fatality_ratio_pregnancy_and_birth_related, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.pregnancy.and.birth.related <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'pregnancy and birth related',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Road Traffic Accident --->
```{r case_fatality_ratio_road_traffic_accident, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.road.traffic.accident <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'road traffic accident',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Ruptured Aortic Aneurysm --->
```{r case_fatality_ratio_ruptured_aortic_aneurysm, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.ruptured.aortic.aneurysm <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'ruptured aortic aneurysm',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Self Harm --->
```{r case_fatality_ratio_self.harm, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.self.harm <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'self harm',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Septic Shock --->
```{r case_fatality_ratio_septic_shock, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.septic.shock <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'septic shock',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Serious Head Injury --->
```{r case_fatality_ratio_serious_head_injury, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.serious.head.injury <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'serious head injury',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Case Fatality Ratio - Stroke Cva --->
```{r case_fatality_ratio_stroke_cva, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
case.fatality.ratio.stroke.cva <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'stroke cva',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Mean Times - Call to Destination --->
```{r ambulance_mean_times_call_to_dest, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.mean.times.call.to.dest <- closed_models(df.lsoa         = amb_mean_times_measure,
                                     df.trust         = amb_mean_times_site_measure,
                                     indicator        = 'ambulance mean times',
                                     sub.indicator    = 'call_to_dest',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Mean Times - Call to Scene Any --->
```{r ambulance_mean_times_call_to_scene_any, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.mean.times.call.to.scene.any <- closed_models(df.lsoa         = amb_mean_times_measure,
                                     df.trust         = amb_mean_times_site_measure,
                                     indicator        = 'ambulance mean times',
                                     sub.indicator    = 'call_to_scene_any',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Mean Times - Call to Scene Conveying --->
```{r ambulance_mean_times_call_to_destination, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.mean.times.call.to.scene.conveying <- closed_models(df.lsoa         = amb_mean_times_measure,
                                     df.trust         = amb_mean_times_site_measure,
                                     indicator        = 'ambulance mean times',
                                     sub.indicator    = 'call_to_scene_conveying',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Mean Times - Destination to Clear --->
```{r ambulance_mean_times_dest_to_clear, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.mean.times.dest.to.clear <- closed_models(df.lsoa         = amb_mean_times_measure,
                                     df.trust         = amb_mean_times_site_measure,
                                     indicator        = 'ambulance mean times',
                                     sub.indicator    = 'dest_to_clear',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Mean Times - Scene to Destination --->
```{r ambulance_mean_times_scene_to_dest, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.mean.times.scene.to.dest <- closed_models(df.lsoa         = amb_mean_times_measure,
                                     df.trust         = amb_mean_times_site_measure,
                                     indicator        = 'ambulance mean times',
                                     sub.indicator    = 'scene_to_dest',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Non-Conveyances - Green Calls --->
```{r ambulance_non_conveyances_green_calls, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.non.conveyances.green.calls <- closed_models(df.lsoa         = amb_non_conveyance_measure,
                                     df.trust         = amb_non_conveyance_site_measure,
                                     indicator        = 'ambulance non-conveyance',
                                     sub.indicator    = 'green calls',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Non-Conveyances - Green Calls Not Conveyed--->
```{r ambulance_non_conveyances_green_calls_not_conveyed, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.non.conveyances.green.calls.non.conveyed <- closed_models(df.lsoa         = amb_non_conveyance_measure,
                                     df.trust         = amb_non_conveyance_site_measure,
                                     indicator        = 'ambulance non-conveyance',
                                     sub.indicator    = 'not conveyed green calls',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Non-Conveyances - Fraction not Conveyed --->
```{r ambulance_non_conveyances_fraction_not_conveyed, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.non.conveyances.fraction.not.conveyed <- closed_models(df.lsoa         = amb_non_conveyance_measure,
                                     df.trust         = amb_non_conveyance_site_measure,
                                     indicator        = 'ambulance non-conveyance',
                                     sub.indicator    = 'fraction not conveyed',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Red Calls - Hospital Transfers --->
```{r ambulance_red_calls_hospital_transfers, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.red.calls.hospital.transfers <- closed_models(df.lsoa         = amb_red_calls_measure,
                                     df.trust         = amb_red_calls_site_measure,
                                     indicator        = 'ambulance red calls',
                                     sub.indicator    = 'hospital transfers',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Red Calls - Total --->
```{r ambulance_red_calls_total, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = FALSE}
ambulance.red.calls.total <- closed_models(df.lsoa         = amb_red_calls_measure,
                                     df.trust         = amb_red_calls_site_measure,
                                     indicator        = 'ambulance red calls',
                                     sub.indicator    = 'total',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3a          = model.opts$mod3a,
                                     model3b          = model.opts$mod3b,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = model.opts$rho.na.rm,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
                                     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Save all objects --->
```{r save_results, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
## save(file = '~/work/closed/knitr/data/summary.RData')
save(diff.time.to.ed,
     check.site,
     check.lsoa,
     mode.of.arrival.any,
     mode.of.arrival.other,
     mode.of.arrival.ambulance,
     unnecessary.attendance,
     all.emergency.admissions.all,
     avoidable.emergency.admissions.any,
     ## avoidable.emergency.admissions.acute.mental.health.crisis,
     ## avoidable.emergency.admissions.angina,
     ## avoidable.emergency.admissions.blocked.catheter,
     ## avoidable.emergency.admissions.cellulitis,
     ## avoidable.emergency.admissions.copd,
     ## avoidable.emergency.admissions.dvt,
     ## avoidable.emergency.admissions.epileptic.fit,
     ## avoidable.emergency.admissions.falls,
     ## avoidable.emergency.admissions.hypoglycaemia,
     ## avoidable.emergency.admissions.minor.head.injuries,
     ## avoidable.emergency.admissions.chest.pain,
     ## avoidable.emergency.admissions.pyrexial.child,
     ## avoidable.emergency.admissions.urinary.tract.infection,
     ed.attendances.admitted.all,
     ed.attendances.admitted.fraction.admitted,
     ed.attendances.admitted.admitted,
     critical.care.cips.all,
     critical.care.cips.critical,
     critical.care.cips.fraction,
     length.of.stay.mean,
     length.of.stay.median,
     case.fatality.ratio.any,
     ## case.fatality.ratio.acute.heart.failure,
     ## case.fatality.ratio.anaphylaxis,
     ## case.fatality.ratio.asphyxiation,
     ## case.fatality.ratio.asthma,
     ## case.fatality.ratio.falls,
     ## case.fatality.ratio.fractured.neck.of.femur,
     ## case.fatality.ratio.meningitis,
     ## case.fatality.ratio.myocardial.infarction,
     ## case.fatality.ratio.pregnancy.and.birth.related,
     ## case.fatality.ratio.road.traffic.accident,
     ## case.fatality.ratio.ruptured.aortic.aneurysm,
     ## case.fatality.ratio.self.harm,
     ## case.fatality.ratio.septic.shock,
     ## case.fatality.ratio.serious.head.injury,
     ## case.fatality.ratio.stroke.cva,
     ## ambulance.mean.times.call.to.dest,
     ## ambulance.mean.times.call.to.scene.any,
     ## ambulance.mean.times.call.to.scene.conveying,
     ## ambulance.mean.times.dest.to.clear,
     ## ambulance.mean.times.scene.to.dest,
     ## ambulance.non.conveyances.green.calls,
     ## ambulance.non.conveyances.green.calls.non.conveyed,
     ## ambulance.non.conveyances.fraction.not.conveyed,
     ## ambulance.red.calls.hospital.transfers,
     ## ambulance.red.calls.total
     ## results,
     ## closure,
     file = '~/work/closed/knitr/data/results.RData')
```

<!--- Load all saved objects --->
```{r load_results, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
load(file = '~/work/closed/knitr/data/results.RData')
## load(file = '~/work/closed/lib/data/summary.RData')
## load(file = '~/work/closed/lib/data/results.regression.RData')
```
