#### Balanced Panels

There is one case site and its four associated contorl sites for which there is missing data (Hemel Hempstead (case), Basingtoke, Warwick, Yeovil) and this is the very first observation in the time series, meaning there are 47 consecutive observations across all outcomes at the site level.

For analyses within site cohorts (i.e. models 1, 2, 3 and 6) this does not present any problem whatsoever, however for pooled analyses across sites this needs dealing with, primarily by ensuring that the panels are balanced.  This has been attempted but results in problems running the analyses due to covariance and is under investigation.  In the interim some of the other analysis options have been investigated as the [panelAR function](https://cran.r-project.org/web/packages/panelAR/panelAR.pdf) has the `seq.times` option which...

> If TRUE, observations are temporally ordered by panel and assigned a sequential time variable that ignores any gaps in the runs

This is what has already been done as part of the data preparation, since the `relative.month` variable derived by Tony Stone ignores the actual month and aligns all time points and has been used as the time variable in the models.  When returning the results `panelAR()` includes an indicator of whether panels are balanced and this has been used to check if the panels are balanced when there is more than one site included (i.e. models 2, 3, 4, 5, 6 and 7)

**TODO** - Include output from panelAR models showing panels are balanced.
