```{r echo = FALSE, cache = FALSE, eval = TRUE}
load('d:/Rpackages/rclosed/data/emergency admissions measure.Rda')
emergency_admissions_measure$sub_measure <- emergency_admissions_measure$measure

```

```{r bishop_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
bishop.admissions.matched <- closed_regress(df            = emergency_admissions_measure,
                                            df.steps      = sites,
		                            site          = 'Bishop Auckland General Hospital',
                                            controls      = 'matched control',
                                            indicator     = 'all emergency admissions',
                                            sub.indicator = 'all emergency admissions',
                                            fit.with      = 'both',
                                            plot          = TRUE,
                                            common.y      = TRUE,
                                            theme         = theme_bw(),
                                            latex         = FALSE,
                                            html          = FALSE)
```
```{r hemel_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hemel.admissions.matched <- closed_regress(df		 = emergency_admissions_measure,
                                           df.steps	 = sites,
                                           site		 = 'Hemel Hempstead Hospital',
                                           controls	 = 'matched control',
                                           indicator	 = 'all emergency admissions',
                                           sub.indicator =  'all emergency admissions',
                                           fit.with	 = 'both',
                                           plot		 = TRUE,
                                           common.y	 = TRUE,
                                           theme	 = theme_bw(),
                                           latex	 = FALSE,
                                           html		 = FALSE)
```
```{r newark_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
newark.admissions.matched <- closed_regress(df            = emergency_admissions_measure,
                                            df.steps      = sites,
                                            site          = 'Newark Hospital',
                                            controls      = 'matched control',
                                            indicator     = 'all emergency admissions',
                                            sub.indicator = 'all emergency admissions',
                                            fit.with      = 'both',
                                            plot          = TRUE,
                                            common.y      = TRUE,
                                            theme         = theme_bw(),
                                            latex         = FALSE,
                                            html          = FALSE)
```
```{r rochdale_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
rochdale.admissions.matched <- closed_regress(df            = emergency_admissions_measure,
                                              df.steps      = sites,
		                              site          = 'Rochdale Infirmary',
                                              controls      = 'matched control',
                                              indicator     = 'all emergency admissions',
                                              sub.indicator = 'all emergency admissions',
                                              fit.with      = 'both',
                                              plot          = TRUE,
					      common.y      = TRUE,
                                              theme         = theme_bw(),
                                              latex         = FALSE,
                                              html          = FALSE)
```
```{r hartlepool_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hartlepool.admissions.matched <- closed_regress(df            = emergency_admissions_measure,
                                                df.steps      = sites,
		                                site          = 'University Hospital of Hartlepool',
                                                controls      = 'matched control',
                                                indicator     = 'all emergency admissions',
                                                sub.indicator = 'all emergency admissions',
                                                fit.with      = 'both',
                                                plot          = TRUE,
						common.y      = TRUE,
                                                theme         = theme_bw(),
                                                latex         = FALSE,
                                                html          = FALSE)
```
```{r echo = FALSE, cache = FALSE, eval = TRUE}
rm(emergency_admissions_measure)
```
