```{r echo = FALSE, cache = FALSE, eval = TRUE}
load('d:/Rpackages/rclosed/data/ed attendances by mode measure.Rda')
```
```{r bishop_attendance_any_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
bishop.attendance.any.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                df.steps      = sites,
		                                site          = 'Bishop Auckland General Hospital',
                                                controls      = 'matched control',
                                                indicator     = 'ed attendances',
                                                sub.indicator = 'any',
                                                covariates    = c('time.to.ed', 'town'),
                                                steps         = c('closure'),
                                                fit.with      = 'both',
                                                plot          = TRUE,
                                                common.y      = TRUE,
                                                theme         = theme_bw(),
                                                latex         = FALSE,
                                                html          = FALSE)
```
```{r bishop_attendance_ambulance_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
bishop.attendance.ambulance.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                      df.steps      = sites,
      		                                      site          = 'Bishop Auckland General Hospital',
                                                      controls      = 'matched control',
                                                      indicator     = 'ed attendances',
                                                      sub.indicator = 'ambulance',
                                                      covariates    = c('time.to.ed', 'town'),
                                                      steps         = c('closure'),
                                                      fit.with      = 'both',
                                                      plot          = TRUE,
                                                      common.y      = TRUE,
                                                      theme         = theme_bw(),
                                                      latex         = FALSE,
                                                      html          = FALSE)
```
```{r bishop_attendance_other_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
bishop.attendance.other.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                  df.steps      = sites,
		                                  site          = 'Bishop Auckland General Hospital',
                                                  controls      = 'matched control',
                                                  indicator     = 'ed attendances',
                                                  sub.indicator = 'other',
                                                  covariates    = c('time.to.ed', 'town'),
                                                  steps         = c('closure'),
                                                  fit.with      = 'both',
                                                  plot          = TRUE,
                                                  common.y      = TRUE,
                                                  theme         = theme_bw(),
                                                  latex         = FALSE,
                                                  html          = FALSE)
```


```{r hemel_attendance_any_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hemel.attendance.any.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                               df.steps      = sites,
                                               site          = 'Hemel Hempstead Hospital',
                                               controls      = 'matched control',
                                               indicator     = 'ed attendances',
                                               sub.indicator = 'any',
                                               covariates    = c('time.to.ed', 'town'),
                                               steps         = c('closure'),
                                               fit.with      = 'both',
                                               plot          = TRUE,
                                               common.y      = TRUE,
                                               theme         = theme_bw(),
                                               latex         = FALSE,
                                               html          = FALSE)
```
```{r hemel_attendance_ambulance_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hemel.attendance.ambulance.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                               df.steps      = sites,
                                               site          = 'Hemel Hempstead Hospital',
                                               controls      = 'matched control',
                                               indicator     = 'ed attendances',
                                               sub.indicator = 'ambulance',
                                               covariates    = c('time.to.ed', 'town'),
                                               steps         = c('closure'),
                                               fit.with      = 'both',
                                               plot          = TRUE,
                                               common.y      = TRUE,
                                               theme         = theme_bw(),
                                               latex         = FALSE,
                                               html          = FALSE)
```
```{r hemel_attendance_other_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hemel.attendance.other.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                               df.steps      = sites,
                                               site          = 'Hemel Hempstead Hospital',
                                               controls      = 'matched control',
                                               indicator     = 'ed attendances',
                                               sub.indicator = 'other',
                                               covariates    = c('time.to.ed', 'town'),
                                               steps         = c('closure'),
                                               fit.with      = 'both',
                                               plot          = TRUE,
                                               common.y      = TRUE,
                                               theme         = theme_bw(),
                                               latex         = FALSE,
                                               html          = FALSE)
```


```{r newark_attendance_any_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
newark.attendance.any.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                df.steps      = sites,
                                                site          = 'Newark Hospital',
                                                controls      = 'matched control',
                                                indicator     = 'ed attendances',
                                                sub.indicator = 'any',
                                                covariates    = c('time.to.ed', 'town'),
                                                steps         = c('closure'),
                                                fit.with      = 'both',
                                                plot          = TRUE,
                                                common.y      = TRUE,
                                                theme         = theme_bw(),
                                                latex         = FALSE,
                                                html          = FALSE)
```
```{r newark_attendance_ambulance_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
newark.attendance.ambulance.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                df.steps      = sites,
                                                site          = 'Newark Hospital',
                                                controls      = 'matched control',
                                                indicator     = 'ed attendances',
                                                sub.indicator = 'ambulance',
                                                covariates    = c('time.to.ed', 'town'),
                                                steps         = c('closure'),
                                                fit.with      = 'both',
                                                plot          = TRUE,
                                                common.y      = TRUE,
                                                theme         = theme_bw(),
                                                latex         = FALSE,
                                                html          = FALSE)
```
```{r newark_attendance_other_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
newark.attendance.other.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                  df.steps      = sites,
                                                  site          = 'Newark Hospital',
                                                  controls      = 'matched control',
                                                  indicator     = 'ed attendances',
                                                  sub.indicator = 'other',
                                                  covariates    = c('time.to.ed', 'town'),
                                                  steps = c('closure'),
                                                  fit.with      = 'both',
                                                  plot          = TRUE,
                                                  common.y      = TRUE,
                                                  theme         = theme_bw(),
                                                  latex         = FALSE,
                                                  html          = FALSE)
```


```{r rochdale_attendance_any_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
rochdale.attendance.any.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                  df.steps      = sites,
                                                  site          = 'Rochdale Infirmary',
                                                  controls      = 'matched control',
                                                  indicator     = 'ed attendances',
                                                  sub.indicator = 'any',
                                                  covariates    = c('time.to.ed', 'town'),
						  steps         = c('closure'),
                                                  fit.with      = 'both',
                                                  plot          = TRUE,
                                                  common.y      = TRUE,
                                                  theme         = theme_bw(),
                                                  latex         = FALSE,
                                                  html          = FALSE)
```
```{r rochdale_attendance_ambulance_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
rochdale.attendance.ambulance.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                        df.steps      = sites,
                                                        site          = 'Rochdale Infirmary',
                                                        controls      = 'matched control',
                                                        indicator     = 'ed attendances',
                                                        sub.indicator = 'ambulance',
                                                        covariates    = c('time.to.ed', 'town'),
                                                        steps         = c('closure'),
                                                        fit.with      = 'both',
                                                        plot          = TRUE,
                                                        common.y      = TRUE,
                                                        theme         = theme_bw(),
                                                        latex         = FALSE,
                                                        html          = FALSE)
```
```{r rochdale_attendance_other_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
rochdale.attendance.other.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                    df.steps      = sites,
                                                    site          = 'Rochdale Infirmary',
                                                    controls      = 'matched control',
                                                    indicator     = 'ed attendances',
                                                    sub.indicator = 'other',
                                                    covariates    = c('time.to.ed', 'town'),
                                                    steps         = c('closure'),
                                                    fit.with      = 'both',
                                                    plot          = TRUE,
                                                    common.y      = TRUE,
                                                    theme         = theme_bw(),
                                                    latex         = FALSE,
                                                    html          = FALSE)
```


```{r hartlepool_attendance_any_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hartlepool.attendance.any.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                    df.steps      = sites,
                                                    site          = 'University Hospital of Hartlepool',
                                                    controls      = 'matched control',
                                                    indicator     = 'ed attendances',
                                                    sub.indicator = 'any',
                                                    covariates    = c('time.to.ed', 'town'),
                                                    steps         = c('closure'),
                                                    fit.with      = 'both',
                                                    plot          = TRUE,
                                                    common.y      = TRUE,
                                                    theme         = theme_bw(),
                                                    latex         = FALSE,
                                                    html          = FALSE)
```
```{r hartlepool_attendance_ambulance_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hartlepool.attendance.ambulance.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                    df.steps      = sites,
                                                    site          = 'University Hospital of Hartlepool',
                                                    controls      = 'matched control',
                                                    indicator     = 'ed attendances',
                                                    sub.indicator = 'ambulance',
                                                    covariates    = c('time.to.ed', 'town'),
                                                    steps         = c('closure'),
                                                    fit.with      = 'both',
                                                    plot          = TRUE,
                                                    common.y      = TRUE,
                                                    theme         = theme_bw(),
                                                    latex         = FALSE,
                                                    html          = FALSE)
```
```{r hartlepool_attendance_other_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hartlepool.attendance.other.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                    df.steps      = sites,
                                                    site          = 'University Hospital of Hartlepool',
                                                    controls      = 'matched control',
                                                    indicator     = 'ed attendances',
                                                    sub.indicator = 'other',
                                                    covariates    = c('time.to.ed', 'town'),
                                                    steps         = c('closure'),
                                                    fit.with      = 'both',
                                                    plot          = TRUE,
                                                    common.y      = TRUE,
                                                    theme         = theme_bw(),
                                                    latex         = FALSE,
                                                    html          = FALSE)
```
```{r all_attendance_any_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
all.attendance.any.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                             df.steps      = sites,
                                             site          = 'All',
                                             controls      = 'matched control',
                                             indicator     = 'ed attendances',
                                             sub.indicator = 'any',
                                             covariates    = c('time.to.ed'),
					     steps         = c('closure'),
                                             fit.with      = 'both',
                                             plot          = TRUE,
                                             common.y      = TRUE,
                                             theme         = theme_bw(),
                                             latex         = FALSE,
                                             html          = FALSE)
```
```{r all_attendance_ambulance_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
all.attendance.ambulance.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                   df.steps      = sites,
                                                   site          = 'All',
                                                   controls      = 'matched control',
                                                   indicator     = 'ed attendances',
                                                   sub.indicator = 'ambulance',
                                                   covariates    = c('time.to.ed'),
			      		     steps         = c('closure'),
                                                   fit.with      = 'both',
                                                   plot          = TRUE,
                                                   common.y      = TRUE,
                                                   theme         = theme_bw(),
                                                   latex         = FALSE,
                                                   html          = FALSE)
```
```{r all_attendance_other_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
all.attendance.other.matched <- closed_regress(df            = ed_attendances_by_mode_measure,
                                               df.steps      = sites,
                                               site          = 'All',
                                               controls      = 'matched control',
                                               indicator     = 'ed attendances',
                                               sub.indicator = 'other',
                                               covariates    = c('time.to.ed'),
                                               steps         = c('closure'),
                                               fit.with      = 'both',
                                               plot          = TRUE,
                                               common.y      = TRUE,
                                               theme         = theme_bw(),
                                               latex         = FALSE,
                                               html          = FALSE)
```
```{r all_attendance_any_pooled, echo = FALSE, cache = FALSE, results = 'hide', eval = FALSE}
all.attendance.any.pooled <- closed_regress(df            = ed_attendances_by_mode_measure,
                                             df.steps      = sites,
                                             site          = 'All',
                                             controls      = 'pooled control',
                                             indicator     = 'ed attendances',
                                             sub.indicator = 'any',
                                             covariates    = c('time.to.ed'),
					     steps         = c('closure'),
                                             fit.with      = 'both',
                                             plot          = TRUE,
                                             common.y      = TRUE,
                                             theme         = theme_bw(),
                                             latex         = FALSE,
                                             html          = FALSE)
```
```{r all_attendance_ambulance_pooled, echo = FALSE, cache = FALSE, results = 'hide', eval = FALSE}
all.attendance.ambulance.pooled <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                   df.steps      = sites,
                                                   site          = 'All',
                                                   controls      = 'pooled control',
                                                   indicator     = 'ed attendances',
                                                   sub.indicator = 'ambulance',
                                                   covariates    = c(''),
                                                   steps         = c('closure'),
                                                   fit.with      = 'both',
                                                   plot          = TRUE,
                                                   common.y      = TRUE,
                                                   theme         = theme_bw(),
                                                   latex         = FALSE,
                                                   html          = FALSE)
```
```{r all_attendance_other_pooled, echo = FALSE, cache = FALSE, results = 'hide', eval = FALSE}
all.attendance.other.pooled <- closed_regress(df            = ed_attendances_by_mode_measure,
                                               df.steps      = sites,
                                               site          = 'All',
                                               controls      = 'pooled control',
                                               indicator     = 'ed attendances',
                                               sub.indicator = 'other',
                                               covariates    = c(''),
                                               steps         = c('closure'),
                                               fit.with      = 'both',
                                               plot          = TRUE,
                                               common.y      = TRUE,
                                               theme         = theme_bw(),
                                               latex         = FALSE,
                                               html          = FALSE)
```
```{r echo = FALSE, cache = FALSE, eval = FALSE}
## Save results for subsequent loading
save(bishop.attendance.any.matched,
     bishop.attendance.ambulance.matched,
     bishop.attendance.other.matched,
     hemmel.attendance.any.matched,
     hemmel.attendance.ambulance.matched,
     hemmel.attendance.other.matched,
     newark.attendance.any.matched,
     newark.attendance.ambulance.matched,
     newark.attendance.other.matched,
     rochdale.attendance.any.matched,
     rochdale.attendance.ambulance.matched,
     rochdale.attendance.other.matched,
     hartlepool.attendance.any.matched,
     hartlepool.attendance.ambulance.matched,
     hartlepool.attendance.other.matched,
     all.attendance.any.matched,
     all.attendance.ambulance.matched,
     all.attendance.other.matched,
     all.attendance.any.pooled,
     all.attendance.ambulance.pooled,
     all.attendance.other.pooled,
     file = 'data/mode_of_arrival.RData')
rm(ed_attendances_by_mode_measure)
```
