### ED Attendance by Mode of Arrival {.tabset .tabset-fade .tabset-pills}

#### All v's  Matched Controls

##### Any

```{r all_attendance_any_matched_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = TRUE}
all.attendance.any.matched$ts.plot.events
```
```{r all_attendance_any_matched_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = TRUE}
all.attendance.any.matched$panelar %>% summary()
```

##### Ambulance

```{r all_attendance_ambulance_matched_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = TRUE}
all.attendance.ambulance.matched$ts.plot.events
```
```{r all_attendance_ambulance_matched_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = TRUE}
all.attendance.ambulance.matched$panelar %>% summary()
```


##### Other

```{r all_attendance_other_matched_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = TRUE}
all.attendance.other.matched$ts.plot.events
```
```{r all_attendance_other_matched_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = TRUE}
all.attendance.other.matched$panelar %>% summary()
```


#### All v's Pooled Controls

**ToDo**

##### Any

```{r all_attendance_any_pooled_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = FALSE}
all.attendance.any.pooled$ts.plot.events
```
```{r all_attendance_any_pooled_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = FALSE}
all.attendance.any.pooled$panelar %>% summary()
```

##### Ambulance

```{r all_attendance_ambulance_pooled_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = FALSE}
all.attendance.ambulance.pooled$ts.plot.events
```
```{r all_attendance_ambulance_pooled_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = FALSE}
all.attendance.ambulance.pooled$panelar %>% summary()
```


##### Other

```{r all_attendance_other_pooled_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = FALSE}
all.attendance.other.pooled$ts.plot.events
```
```{r all_attendance_other_pooled_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = FALSE}
all.attendance.other.pooled$panelar %>% summary()
```
