```{r echo = FALSE, cache = FALSE, eval = FALSE}
load('d:/Rpackages/rclosed/data/ed attendances by mode measure.Rda')
```


```{r echo = FALSE, cache = FALSE, results = 'hide', eval = FALSE}
bishop.attendance.arrival.any <- closed_regress(df            = ed_attendances_by_mode_measure,
                                                df.steps      = sites,
		                                site          = 'Bishop Auckland General Hospital',
                                                controls      = 'matched control',
                                                indicator     = 'ed attendances',
                                                sub.indicator = 'any',
                                                fit.with      = 'both',
                                                plot          = TRUE,
                                                theme         = theme_bw(),
                                                latex         = FALSE,
                                                html          = FALSE)
```






```{r echo = FALSE, cache = FALSE, eval = FALSE}
rm(ed_attendances_by_mode_measure)

```
