The following table tabulates the coefficients for the key variable of interest (`closure`) for each of the outcomes and each model.


```{r regression_summary_table, echo = FALSE, cache = FALSE, results = 'hide', eval = FALSE}
## Build a data frame of all of the coefficients by model type
attendance.model1 <- rbind(mode.of.arrival.any$model1.panelar.bishop.coef,
                                mode.of.arrival.any$model1.panelar.hartlepool.coef,
                                mode.of.arrival.any$model1.panelar.hemel.coef,
                                mode.of.arrival.any$model1.panelar.newark.coef,
                                mode.of.arrival.any$model1.panelar.rochdale.coef,
                                mode.of.arrival.other$model1.panelar.bishop.coef,
                                mode.of.arrival.other$model1.panelar.hartlepool.coef,
                                mode.of.arrival.other$model1.panelar.hemel.coef,
                                mode.of.arrival.other$model1.panelar.newark.coef,
                                mode.of.arrival.other$model1.panelar.rochdale.coef,
                                mode.of.arrival.ambulance$model1.panelar.bishop.coef,
                                mode.of.arrival.ambulance$model1.panelar.hartlepool.coef,
                                mode.of.arrival.ambulance$model1.panelar.hemel.coef,
                                mode.of.arrival.ambulance$model1.panelar.newark.coef,
                                mode.of.arrival.ambulance$model1.panelar.rochdale.coef,
                                unnecessary.attendance$model1.panelar.bishop.coef,
                                unnecessary.attendance$model1.panelar.hartlepool.coef,
                                unnecessary.attendance$model1.panelar.hemel.coef,
                                unnecessary.attendance$model1.panelar.newark.coef,
                                unnecessary.attendance$model1.panelar.rochdale.coef)
avoidable.model1 <- rbind(avoidable.emergency.admissions.any$model1.panelar.bishop.coef,
                          avoidable.emergency.admissions.any$model1.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.any$model1.panelar.hemel.coef,
                          avoidable.emergency.admissions.any$model1.panelar.newark.coef,
                          avoidable.emergency.admissions.any$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.angina$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.angina$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.angina$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.angina$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.angina$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.cellulitis$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.cellulitis$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.cellulitis$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.cellulitis$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.cellulitis$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.copd$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.copd$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.copd$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.copd$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.copd$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.dvt$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.dvt$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.dvt$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.dvt$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.dvt$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.falls$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.falls$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.falls$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.falls$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.falls$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model1.panelar.rochdale.coef,
                          avoidable.emergency.admissions.chest.pain$model1.panelar.bishop.coef,
                          avoidable.emergency.admissions.chest.pain$model1.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.chest.pain$model1.panelar.hemel.coef,
                          avoidable.emergency.admissions.chest.pain$model1.panelar.newark.coef,
                          avoidable.emergency.admissions.chest.pain$model1.panelar.rochdale.coef)
                          ## avoidable.emergency.admissions.pyrexial.child$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model1.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model1.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model1.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model1.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model1.panelar.newark.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model1.panelar.rochdale.coef)
admissions.model1 <- rbind(all.emergency.admissions.all$model1.panelar.bishop.coef,
                           all.emergency.admissions.all$model1.panelar.hartlepool.coef,
                           all.emergency.admissions.all$model1.panelar.hemel.coef,
                           all.emergency.admissions.all$model1.panelar.newark.coef,
                           all.emergency.admissions.all$model1.panelar.rochdale.coef,
                           ed.attendances.admitted.all$model1.panelar.bishop.coef,
                           ed.attendances.admitted.all$model1.panelar.hartlepool.coef,
                           ed.attendances.admitted.all$model1.panelar.hemel.coef,
                           ed.attendances.admitted.all$model1.panelar.newark.coef,
                           ed.attendances.admitted.all$model1.panelar.rochdale.coef,
                           ed.attendances.admitted.fraction.admitted$model1.panelar.bishop.coef,
                           ed.attendances.admitted.fraction.admitted$model1.panelar.hartlepool.coef,
                           ed.attendances.admitted.fraction.admitted$model1.panelar.hemel.coef,
                           ed.attendances.admitted.fraction.admitted$model1.panelar.newark.coef,
                           ed.attendances.admitted.fraction.admitted$model1.panelar.rochdale.coef,
                           ed.attendances.admitted.admitted$model1.panelar.bishop.coef,
                           ed.attendances.admitted.admitted$model1.panelar.hartlepool.coef,
                           ed.attendances.admitted.admitted$model1.panelar.hemel.coef,
                           ed.attendances.admitted.admitted$model1.panelar.newark.coef,
                           ed.attendances.admitted.admitted$model1.panelar.rochdale.coef,
                           critical.care.cips.all$model1.panelar.bishop.coef,
                           critical.care.cips.all$model1.panelar.hartlepool.coef,
                           critical.care.cips.all$model1.panelar.hemel.coef,
                           critical.care.cips.all$model1.panelar.newark.coef,
                           critical.care.cips.all$model1.panelar.rochdale.coef,
                           critical.care.cips.critical$model1.panelar.bishop.coef,
                           critical.care.cips.critical$model1.panelar.hartlepool.coef,
                           critical.care.cips.critical$model1.panelar.hemel.coef,
                           critical.care.cips.critical$model1.panelar.newark.coef,
                           critical.care.cips.critical$model1.panelar.rochdale.coef,
                           critical.care.cips.fraction$model1.panelar.bishop.coef,
                           critical.care.cips.fraction$model1.panelar.hartlepool.coef,
                           critical.care.cips.fraction$model1.panelar.hemel.coef,
                           critical.care.cips.fraction$model1.panelar.newark.coef,
                           critical.care.cips.fraction$model1.panelar.rochdale.coef)
length.of.stay.model1 <- rbind(length.of.stay.mean$model1.panelar.bishop.coef,
                               length.of.stay.mean$model1.panelar.hartlepool.coef,
                               length.of.stay.mean$model1.panelar.hemel.coef,
                               length.of.stay.mean$model1.panelar.newark.coef,
                               length.of.stay.mean$model1.panelar.rochdale.coef,
                               length.of.stay.median$model1.panelar.bishop.coef,
                               length.of.stay.median$model1.panelar.hartlepool.coef,
                               length.of.stay.median$model1.panelar.hemel.coef,
                               length.of.stay.median$model1.panelar.newark.coef,
                               length.of.stay.median$model1.panelar.rochdale.coef)
case.fatality.model1 <- rbind(case.fatality.ratio.any$model1.panelar.bishop.coef,
                              case.fatality.ratio.any$model1.panelar.hartlepool.coef,
                              case.fatality.ratio.any$model1.panelar.hemel.coef,
                              case.fatality.ratio.any$model1.panelar.newark.coef,
                              case.fatality.ratio.any$model1.panelar.rochdale.coef)
                              ## case.fatality.ratio.acute.heart.failure$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.acute.heart.failure$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.acute.heart.failure$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.acute.heart.failure$model1.panelar.newark.coef,
                              ## case.fatality.ratio.acute.heart.failure$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.anaphylaxis$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.anaphylaxis$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.anaphylaxis$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.anaphylaxis$model1.panelar.newark.coef,
                              ## case.fatality.ratio.anaphylaxis$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.asthma$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.asthma$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.asthma$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.asthma$model1.panelar.newark.coef,
                              ## case.fatality.ratio.asthma$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.falls$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.falls$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.falls$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.falls$model1.panelar.newark.coef,
                              ## case.fatality.ratio.falls$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model1.panelar.newark.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.meningitis$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.meningitis$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.meningitis$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.meningitis$model1.panelar.newark.coef,
                              ## case.fatality.ratio.meningitis$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.myocardial.infarction$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.myocardial.infarction$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.myocardial.infarction$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.myocardial.infarction$model1.panelar.newark.coef,
                              ## case.fatality.ratio.myocardial.infarction$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model1.panelar.newark.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.road.traffic.accident$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.road.traffic.accident$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.road.traffic.accident$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.road.traffic.accident$model1.panelar.newark.coef,
                              ## case.fatality.ratio.road.traffic.accident$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model1.panelar.newark.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.self.harm$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.self.harm$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.self.harm$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.self.harm$model1.panelar.newark.coef,
                              ## case.fatality.ratio.self.harm$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.septic.shock$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.septic.shock$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.septic.shock$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.septic.shock$model1.panelar.newark.coef,
                              ## case.fatality.ratio.septic.shock$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.serious.head.injury$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.serious.head.injury$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.serious.head.injury$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.serious.head.injury$model1.panelar.newark.coef,
                              ## case.fatality.ratio.serious.head.injury$model1.panelar.rochdale.coef,
                              ## case.fatality.ratio.stroke.cva$model1.panelar.bishop.coef,
                              ## case.fatality.ratio.stroke.cva$model1.panelar.hartlepool.coef,
                              ## case.fatality.ratio.stroke.cva$model1.panelar.hemel.coef,
                              ## case.fatality.ratio.stroke.cva$model1.panelar.newark.coef,
                              ## case.fatality.ratio.stroke.cva$model1.panelar.rochdale.coef)
## ambulance.times.model1 <- rbind(ambulance.mean.times.call.to.dest$model1.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.dest$model1.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.dest$model1.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.dest$model1.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.dest$model1.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model1.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model1.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model1.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model1.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model1.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model1.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model1.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model1.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model1.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model1.panelar.rochdale.coef,
                                   ## ambulance.mean.times.dest.to.clear$model1.panelar.bishop.coef,
                                   ## ambulance.mean.times.dest.to.clear$model1.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.dest.to.clear$model1.panelar.hemel.coef,
                                   ## ambulance.mean.times.dest.to.clear$model1.panelar.newark.coef,
                                   ## ambulance.mean.times.dest.to.clear$model1.panelar.rochdale.coef,
                                   ## ambulance.mean.times.scene.to.dest$model1.panelar.bishop.coef,
                                   ## ambulance.mean.times.scene.to.dest$model1.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.scene.to.dest$model1.panelar.hemel.coef,
                                   ## ambulance.mean.times.scene.to.dest$model1.panelar.newark.coef,
                                   ## ambulance.mean.times.scene.to.dest$model1.panelar.rochdale.coef)
attendance.model1$model          <- 'Model 1'
avoidable.model1$model           <- 'Model 1'
admissions.model1$model          <- 'Model 1'
length.of.stay.model1$model      <- 'Model 1'
case.fatality.model1$model       <- 'Model 1'
## ambulance.times.model1$model     <- 'Model 1'
results.model1 <-rbind(attendance.model1,
                       avoidable.model1,
                       admissions.model1,
                       length.of.stay.model1,
                       case.fatality.model1)
                       ## ambulance.times)
rm(attendance.model1,
   avoidable.model1,
   admissions.model1,
   length.of.stay.model1,
   case.fatality.model1)
   ## ambulance.times)

## Model 2
attendance.model2 <- rbind(mode.of.arrival.any$model2.panelar.bishop.coef,
                                mode.of.arrival.any$model2.panelar.hartlepool.coef,
                                mode.of.arrival.any$model2.panelar.hemel.coef,
                                mode.of.arrival.any$model2.panelar.newark.coef,
                                mode.of.arrival.any$model2.panelar.rochdale.coef,
                                mode.of.arrival.other$model2.panelar.bishop.coef,
                                mode.of.arrival.other$model2.panelar.hartlepool.coef,
                                mode.of.arrival.other$model2.panelar.hemel.coef,
                                mode.of.arrival.other$model2.panelar.newark.coef,
                                mode.of.arrival.other$model2.panelar.rochdale.coef,
                                mode.of.arrival.ambulance$model2.panelar.bishop.coef,
                                mode.of.arrival.ambulance$model2.panelar.hartlepool.coef,
                                mode.of.arrival.ambulance$model2.panelar.hemel.coef,
                                mode.of.arrival.ambulance$model2.panelar.newark.coef,
                                mode.of.arrival.ambulance$model2.panelar.rochdale.coef,
                                unnecessary.attendance$model2.panelar.bishop.coef,
                                unnecessary.attendance$model2.panelar.hartlepool.coef,
                                unnecessary.attendance$model2.panelar.hemel.coef,
                                unnecessary.attendance$model2.panelar.newark.coef,
                                unnecessary.attendance$model2.panelar.rochdale.coef)
avoidable.model2 <- rbind(avoidable.emergency.admissions.any$model2.panelar.bishop.coef,
                          avoidable.emergency.admissions.any$model2.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.any$model2.panelar.hemel.coef,
                          avoidable.emergency.admissions.any$model2.panelar.newark.coef,
                          avoidable.emergency.admissions.any$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.angina$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.angina$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.angina$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.angina$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.angina$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.cellulitis$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.cellulitis$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.cellulitis$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.cellulitis$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.cellulitis$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.copd$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.copd$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.copd$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.copd$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.copd$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.dvt$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.dvt$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.dvt$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.dvt$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.dvt$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.falls$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.falls$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.falls$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.falls$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.falls$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model2.panelar.rochdale.coef,
                          avoidable.emergency.admissions.chest.pain$model2.panelar.bishop.coef,
                          avoidable.emergency.admissions.chest.pain$model2.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.chest.pain$model2.panelar.hemel.coef,
                          avoidable.emergency.admissions.chest.pain$model2.panelar.newark.coef,
                          avoidable.emergency.admissions.chest.pain$model2.panelar.rochdale.coef)
                          ## avoidable.emergency.admissions.pyrexial.child$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model2.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model2.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model2.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model2.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model2.panelar.newark.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model2.panelar.rochdale.coef)
admissions.model2 <- rbind(all.emergency.admissions.all$model2.panelar.bishop.coef,
                           all.emergency.admissions.all$model2.panelar.hartlepool.coef,
                           all.emergency.admissions.all$model2.panelar.hemel.coef,
                           all.emergency.admissions.all$model2.panelar.newark.coef,
                           all.emergency.admissions.all$model2.panelar.rochdale.coef,
                           ed.attendances.admitted.all$model2.panelar.bishop.coef,
                           ed.attendances.admitted.all$model2.panelar.hartlepool.coef,
                           ed.attendances.admitted.all$model2.panelar.hemel.coef,
                           ed.attendances.admitted.all$model2.panelar.newark.coef,
                           ed.attendances.admitted.all$model2.panelar.rochdale.coef,
                           ed.attendances.admitted.fraction.admitted$model2.panelar.bishop.coef,
                           ed.attendances.admitted.fraction.admitted$model2.panelar.hartlepool.coef,
                           ed.attendances.admitted.fraction.admitted$model2.panelar.hemel.coef,
                           ed.attendances.admitted.fraction.admitted$model2.panelar.newark.coef,
                           ed.attendances.admitted.fraction.admitted$model2.panelar.rochdale.coef,
                           ed.attendances.admitted.admitted$model2.panelar.bishop.coef,
                           ed.attendances.admitted.admitted$model2.panelar.hartlepool.coef,
                           ed.attendances.admitted.admitted$model2.panelar.hemel.coef,
                           ed.attendances.admitted.admitted$model2.panelar.newark.coef,
                           ed.attendances.admitted.admitted$model2.panelar.rochdale.coef,
                           critical.care.cips.all$model2.panelar.bishop.coef,
                           critical.care.cips.all$model2.panelar.hartlepool.coef,
                           critical.care.cips.all$model2.panelar.hemel.coef,
                           critical.care.cips.all$model2.panelar.newark.coef,
                           critical.care.cips.all$model2.panelar.rochdale.coef,
                           critical.care.cips.critical$model2.panelar.bishop.coef,
                           critical.care.cips.critical$model2.panelar.hartlepool.coef,
                           critical.care.cips.critical$model2.panelar.hemel.coef,
                           critical.care.cips.critical$model2.panelar.newark.coef,
                           critical.care.cips.critical$model2.panelar.rochdale.coef,
                           critical.care.cips.fraction$model2.panelar.bishop.coef,
                           critical.care.cips.fraction$model2.panelar.hartlepool.coef,
                           critical.care.cips.fraction$model2.panelar.hemel.coef,
                           critical.care.cips.fraction$model2.panelar.newark.coef,
                           critical.care.cips.fraction$model2.panelar.rochdale.coef)
length.of.stay.model2 <- rbind(length.of.stay.mean$model2.panelar.bishop.coef,
                               length.of.stay.mean$model2.panelar.hartlepool.coef,
                               length.of.stay.mean$model2.panelar.hemel.coef,
                               length.of.stay.mean$model2.panelar.newark.coef,
                               length.of.stay.mean$model2.panelar.rochdale.coef,
                               length.of.stay.median$model2.panelar.bishop.coef,
                               length.of.stay.median$model2.panelar.hartlepool.coef,
                               length.of.stay.median$model2.panelar.hemel.coef,
                               length.of.stay.median$model2.panelar.newark.coef,
                               length.of.stay.median$model2.panelar.rochdale.coef)
case.fatality.model2 <- rbind(case.fatality.ratio.any$model2.panelar.bishop.coef,
                              case.fatality.ratio.any$model2.panelar.hartlepool.coef,
                              case.fatality.ratio.any$model2.panelar.hemel.coef,
                              case.fatality.ratio.any$model2.panelar.newark.coef,
                              case.fatality.ratio.any$model2.panelar.rochdale.coef)
                              ## case.fatality.ratio.acute.heart.failure$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.acute.heart.failure$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.acute.heart.failure$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.acute.heart.failure$model2.panelar.newark.coef,
                              ## case.fatality.ratio.acute.heart.failure$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.anaphylaxis$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.anaphylaxis$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.anaphylaxis$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.anaphylaxis$model2.panelar.newark.coef,
                              ## case.fatality.ratio.anaphylaxis$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.asthma$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.asthma$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.asthma$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.asthma$model2.panelar.newark.coef,
                              ## case.fatality.ratio.asthma$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.falls$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.falls$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.falls$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.falls$model2.panelar.newark.coef,
                              ## case.fatality.ratio.falls$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model2.panelar.newark.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.meningitis$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.meningitis$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.meningitis$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.meningitis$model2.panelar.newark.coef,
                              ## case.fatality.ratio.meningitis$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.myocardial.infarction$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.myocardial.infarction$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.myocardial.infarction$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.myocardial.infarction$model2.panelar.newark.coef,
                              ## case.fatality.ratio.myocardial.infarction$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model2.panelar.newark.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.road.traffic.accident$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.road.traffic.accident$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.road.traffic.accident$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.road.traffic.accident$model2.panelar.newark.coef,
                              ## case.fatality.ratio.road.traffic.accident$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model2.panelar.newark.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.self.harm$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.self.harm$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.self.harm$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.self.harm$model2.panelar.newark.coef,
                              ## case.fatality.ratio.self.harm$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.septic.shock$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.septic.shock$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.septic.shock$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.septic.shock$model2.panelar.newark.coef,
                              ## case.fatality.ratio.septic.shock$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.serious.head.injury$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.serious.head.injury$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.serious.head.injury$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.serious.head.injury$model2.panelar.newark.coef,
                              ## case.fatality.ratio.serious.head.injury$model2.panelar.rochdale.coef,
                              ## case.fatality.ratio.stroke.cva$model2.panelar.bishop.coef,
                              ## case.fatality.ratio.stroke.cva$model2.panelar.hartlepool.coef,
                              ## case.fatality.ratio.stroke.cva$model2.panelar.hemel.coef,
                              ## case.fatality.ratio.stroke.cva$model2.panelar.newark.coef,
                              ## case.fatality.ratio.stroke.cva$model2.panelar.rochdale.coef)
## ambulance.times.model2 <- rbind(ambulance.mean.times.call.to.dest$model2.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.dest$model2.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.dest$model2.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.dest$model2.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.dest$model2.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model2.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model2.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model2.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model2.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model2.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model2.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model2.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model2.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model2.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model2.panelar.rochdale.coef,
                                   ## ambulance.mean.times.dest.to.clear$model2.panelar.bishop.coef,
                                   ## ambulance.mean.times.dest.to.clear$model2.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.dest.to.clear$model2.panelar.hemel.coef,
                                   ## ambulance.mean.times.dest.to.clear$model2.panelar.newark.coef,
                                   ## ambulance.mean.times.dest.to.clear$model2.panelar.rochdale.coef,
                                   ## ambulance.mean.times.scene.to.dest$model2.panelar.bishop.coef,
                                   ## ambulance.mean.times.scene.to.dest$model2.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.scene.to.dest$model2.panelar.hemel.coef,
                                   ## ambulance.mean.times.scene.to.dest$model2.panelar.newark.coef,
                                   ## ambulance.mean.times.scene.to.dest$model2.panelar.rochdale.coef)
attendance.model2$model          <- 'Model 2'
avoidable.model2$model           <- 'Model 2'
admissions.model2$model          <- 'Model 2'
length.of.stay.model2$model      <- 'Model 2'
case.fatality.model2$model       <- 'Model 2'
## ambulance.times.model2$model     <- 'Model 2'
results.model2 <-rbind(attendance.model2,
                       avoidable.model2,
                       admissions.model2,
                       length.of.stay.model2,
                       case.fatality.model2)
                       ## ambulance.times)
rm(attendance.model2,
   avoidable.model2,
   admissions.model2,
   length.of.stay.model2,
   case.fatality.model2)
## ambulance.times)

## Model 3
attendance.model3 <- rbind(mode.of.arrival.any$model3.panelar.bishop.coef,
                                mode.of.arrival.any$model3.panelar.hartlepool.coef,
                                mode.of.arrival.any$model3.panelar.hemel.coef,
                                mode.of.arrival.any$model3.panelar.newark.coef,
                                mode.of.arrival.any$model3.panelar.rochdale.coef,
                                mode.of.arrival.other$model3.panelar.bishop.coef,
                                mode.of.arrival.other$model3.panelar.hartlepool.coef,
                                mode.of.arrival.other$model3.panelar.hemel.coef,
                                mode.of.arrival.other$model3.panelar.newark.coef,
                                mode.of.arrival.other$model3.panelar.rochdale.coef,
                                mode.of.arrival.ambulance$model3.panelar.bishop.coef,
                                mode.of.arrival.ambulance$model3.panelar.hartlepool.coef,
                                mode.of.arrival.ambulance$model3.panelar.hemel.coef,
                                mode.of.arrival.ambulance$model3.panelar.newark.coef,
                                mode.of.arrival.ambulance$model3.panelar.rochdale.coef,
                                unnecessary.attendance$model3.panelar.bishop.coef,
                                unnecessary.attendance$model3.panelar.hartlepool.coef,
                                unnecessary.attendance$model3.panelar.hemel.coef,
                                unnecessary.attendance$model3.panelar.newark.coef,
                                unnecessary.attendance$model3.panelar.rochdale.coef)
avoidable.model3 <- rbind(avoidable.emergency.admissions.any$model3.panelar.bishop.coef,
                          avoidable.emergency.admissions.any$model3.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.any$model3.panelar.hemel.coef,
                          avoidable.emergency.admissions.any$model3.panelar.newark.coef,
                          avoidable.emergency.admissions.any$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.angina$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.angina$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.angina$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.angina$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.angina$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.cellulitis$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.cellulitis$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.cellulitis$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.cellulitis$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.cellulitis$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.copd$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.copd$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.copd$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.copd$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.copd$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.dvt$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.dvt$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.dvt$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.dvt$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.dvt$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.falls$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.falls$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.falls$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.falls$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.falls$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model3.panelar.rochdale.coef,
                          avoidable.emergency.admissions.chest.pain$model3.panelar.bishop.coef,
                          avoidable.emergency.admissions.chest.pain$model3.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.chest.pain$model3.panelar.hemel.coef,
                          avoidable.emergency.admissions.chest.pain$model3.panelar.newark.coef,
                          avoidable.emergency.admissions.chest.pain$model3.panelar.rochdale.coef)
                          ## avoidable.emergency.admissions.pyrexial.child$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model3.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model3.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model3.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model3.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model3.panelar.newark.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model3.panelar.rochdale.coef)
admissions.model3 <- rbind(all.emergency.admissions.all$model3.panelar.bishop.coef,
                           all.emergency.admissions.all$model3.panelar.hartlepool.coef,
                           all.emergency.admissions.all$model3.panelar.hemel.coef,
                           all.emergency.admissions.all$model3.panelar.newark.coef,
                           all.emergency.admissions.all$model3.panelar.rochdale.coef,
                           ed.attendances.admitted.all$model3.panelar.bishop.coef,
                           ed.attendances.admitted.all$model3.panelar.hartlepool.coef,
                           ed.attendances.admitted.all$model3.panelar.hemel.coef,
                           ed.attendances.admitted.all$model3.panelar.newark.coef,
                           ed.attendances.admitted.all$model3.panelar.rochdale.coef,
                           ed.attendances.admitted.fraction.admitted$model3.panelar.bishop.coef,
                           ed.attendances.admitted.fraction.admitted$model3.panelar.hartlepool.coef,
                           ed.attendances.admitted.fraction.admitted$model3.panelar.hemel.coef,
                           ed.attendances.admitted.fraction.admitted$model3.panelar.newark.coef,
                           ed.attendances.admitted.fraction.admitted$model3.panelar.rochdale.coef,
                           ed.attendances.admitted.admitted$model3.panelar.bishop.coef,
                           ed.attendances.admitted.admitted$model3.panelar.hartlepool.coef,
                           ed.attendances.admitted.admitted$model3.panelar.hemel.coef,
                           ed.attendances.admitted.admitted$model3.panelar.newark.coef,
                           ed.attendances.admitted.admitted$model3.panelar.rochdale.coef,
                           critical.care.cips.all$model3.panelar.bishop.coef,
                           critical.care.cips.all$model3.panelar.hartlepool.coef,
                           critical.care.cips.all$model3.panelar.hemel.coef,
                           critical.care.cips.all$model3.panelar.newark.coef,
                           critical.care.cips.all$model3.panelar.rochdale.coef,
                           critical.care.cips.critical$model3.panelar.bishop.coef,
                           critical.care.cips.critical$model3.panelar.hartlepool.coef,
                           critical.care.cips.critical$model3.panelar.hemel.coef,
                           critical.care.cips.critical$model3.panelar.newark.coef,
                           critical.care.cips.critical$model3.panelar.rochdale.coef,
                           critical.care.cips.fraction$model3.panelar.bishop.coef,
                           critical.care.cips.fraction$model3.panelar.hartlepool.coef,
                           critical.care.cips.fraction$model3.panelar.hemel.coef,
                           critical.care.cips.fraction$model3.panelar.newark.coef,
                           critical.care.cips.fraction$model3.panelar.rochdale.coef)
length.of.stay.model3 <- rbind(length.of.stay.mean$model3.panelar.bishop.coef,
                               length.of.stay.mean$model3.panelar.hartlepool.coef,
                               length.of.stay.mean$model3.panelar.hemel.coef,
                               length.of.stay.mean$model3.panelar.newark.coef,
                               length.of.stay.mean$model3.panelar.rochdale.coef,
                               length.of.stay.median$model3.panelar.bishop.coef,
                               length.of.stay.median$model3.panelar.hartlepool.coef,
                               length.of.stay.median$model3.panelar.hemel.coef,
                               length.of.stay.median$model3.panelar.newark.coef,
                               length.of.stay.median$model3.panelar.rochdale.coef)
case.fatality.model3 <- rbind(case.fatality.ratio.any$model3.panelar.bishop.coef,
                              case.fatality.ratio.any$model3.panelar.hartlepool.coef,
                              case.fatality.ratio.any$model3.panelar.hemel.coef,
                              case.fatality.ratio.any$model3.panelar.newark.coef,
                              case.fatality.ratio.any$model3.panelar.rochdale.coef)
                              ## case.fatality.ratio.acute.heart.failure$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.acute.heart.failure$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.acute.heart.failure$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.acute.heart.failure$model3.panelar.newark.coef,
                              ## case.fatality.ratio.acute.heart.failure$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.anaphylaxis$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.anaphylaxis$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.anaphylaxis$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.anaphylaxis$model3.panelar.newark.coef,
                              ## case.fatality.ratio.anaphylaxis$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.asthma$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.asthma$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.asthma$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.asthma$model3.panelar.newark.coef,
                              ## case.fatality.ratio.asthma$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.falls$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.falls$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.falls$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.falls$model3.panelar.newark.coef,
                              ## case.fatality.ratio.falls$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model3.panelar.newark.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.meningitis$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.meningitis$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.meningitis$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.meningitis$model3.panelar.newark.coef,
                              ## case.fatality.ratio.meningitis$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.myocardial.infarction$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.myocardial.infarction$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.myocardial.infarction$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.myocardial.infarction$model3.panelar.newark.coef,
                              ## case.fatality.ratio.myocardial.infarction$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model3.panelar.newark.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.road.traffic.accident$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.road.traffic.accident$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.road.traffic.accident$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.road.traffic.accident$model3.panelar.newark.coef,
                              ## case.fatality.ratio.road.traffic.accident$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model3.panelar.newark.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.self.harm$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.self.harm$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.self.harm$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.self.harm$model3.panelar.newark.coef,
                              ## case.fatality.ratio.self.harm$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.septic.shock$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.septic.shock$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.septic.shock$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.septic.shock$model3.panelar.newark.coef,
                              ## case.fatality.ratio.septic.shock$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.serious.head.injury$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.serious.head.injury$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.serious.head.injury$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.serious.head.injury$model3.panelar.newark.coef,
                              ## case.fatality.ratio.serious.head.injury$model3.panelar.rochdale.coef,
                              ## case.fatality.ratio.stroke.cva$model3.panelar.bishop.coef,
                              ## case.fatality.ratio.stroke.cva$model3.panelar.hartlepool.coef,
                              ## case.fatality.ratio.stroke.cva$model3.panelar.hemel.coef,
                              ## case.fatality.ratio.stroke.cva$model3.panelar.newark.coef,
                              ## case.fatality.ratio.stroke.cva$model3.panelar.rochdale.coef)
## ambulance.times.model3 <- rbind(ambulance.mean.times.call.to.dest$model3.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.dest$model3.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.dest$model3.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.dest$model3.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.dest$model3.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model3.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model3.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model3.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model3.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model3.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model3.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model3.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model3.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model3.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model3.panelar.rochdale.coef,
                                   ## ambulance.mean.times.dest.to.clear$model3.panelar.bishop.coef,
                                   ## ambulance.mean.times.dest.to.clear$model3.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.dest.to.clear$model3.panelar.hemel.coef,
                                   ## ambulance.mean.times.dest.to.clear$model3.panelar.newark.coef,
                                   ## ambulance.mean.times.dest.to.clear$model3.panelar.rochdale.coef,
                                   ## ambulance.mean.times.scene.to.dest$model3.panelar.bishop.coef,
                                   ## ambulance.mean.times.scene.to.dest$model3.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.scene.to.dest$model3.panelar.hemel.coef,
                                   ## ambulance.mean.times.scene.to.dest$model3.panelar.newark.coef,
                                   ## ambulance.mean.times.scene.to.dest$model3.panelar.rochdale.coef)
attendance.model3$model          <- 'Model 3'
avoidable.model3$model           <- 'Model 3'
admissions.model3$model          <- 'Model 3'
length.of.stay.model3$model      <- 'Model 3'
case.fatality.model3$model       <- 'Model 3'
## ambulance.times.model3$model     <- 'Model 3'
results.model3 <-rbind(attendance.model3,
                       avoidable.model3,
                       admissions.model3,
                       length.of.stay.model3,
                       case.fatality.model3)
                       ## ambulance.times)
rm(attendance.model3,
   avoidable.model3,
   admissions.model3,
   length.of.stay.model3,
   case.fatality.model3)
## ambulance.times)

## Model 4
attendance.model4 <- rbind(mode.of.arrival.any$model4.panelar.coef,
                           mode.of.arrival.other$model4.panelar.coef,
                           mode.of.arrival.ambulance$model4.panelar.coef,
                           unnecessary.attendance$model4.panelar.coef)
avoidable.model4 <- rbind(avoidable.emergency.admissions.any$model4.panelar.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model4.panelar.coef,
                          ## avoidable.emergency.admissions.angina$model4.panelar.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model4.panelar.coef,
                          ## avoidable.emergency.admissions.cellulitis$model4.panelar.coef,
                          ## avoidable.emergency.admissions.copd$model4.panelar.coef,
                          ## avoidable.emergency.admissions.dvt$model4.panelar.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model4.panelar.coef,
                          ## avoidable.emergency.admissions.falls$model4.panelar.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model4.panelar.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model4.panelar.coef,
                          avoidable.emergency.admissions.chest.pain$model4.panelar.coef)
                          ## avoidable.emergency.admissions.pyrexial.child$model4.panelar.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model4.panelar.coef)
admissions.model4 <- rbind(all.emergency.admissions.all$model4.panelar.coef,
                           ed.attendances.admitted.all$model4.panelar.coef,
                           ed.attendances.admitted.fraction.admitted$model4.panelar.coef,
                           ed.attendances.admitted.admitted$model4.panelar.coef,
                           critical.care.cips.all$model4.panelar.coef,
                           critical.care.cips.critical$model4.panelar.coef,
                           critical.care.cips.fraction$model4.panelar.coef)
length.of.stay.model4 <- rbind(length.of.stay.mean$model4.panelar.coef,
                               length.of.stay.median$model4.panelar.coef)
case.fatality.model4 <- rbind(case.fatality.ratio.any$model4.panelar.coef)
                              ## case.fatality.ratio.acute.heart.failure$model4.panelar.coef,
                              ## case.fatality.ratio.anaphylaxis$model4.panelar.coef,
                              ## case.fatality.ratio.asthma$model4.panelar.coef,
                              ## case.fatality.ratio.falls$model4.panelar.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model4.panelar.coef,
                              ## case.fatality.ratio.meningitis$model4.panelar.coef,
                              ## case.fatality.ratio.myocardial.infarction$model4.panelar.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model4.panelar.coef,
                              ## case.fatality.ratio.road.traffic.accident$model4.panelar.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model4.panelar.coef,
                              ## case.fatality.ratio.self.harm$model4.panelar.coef,
                              ## case.fatality.ratio.septic.shock$model4.panelar.coef,
                              ## case.fatality.ratio.serious.head.injury$model4.panelar.coef,
                              ## case.fatality.ratio.stroke.cva$model4.panelar.coef)
## ambulance.times.model4 <- rbind(ambulance.mean.times.call.to.dest$model4.panelar.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model4.panelar.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model4.panelar.coef,
                                   ## ambulance.mean.times.dest.to.clear$model4.panelar.coef,
                                   ## ambulance.mean.times.scene.to.dest$model4.panelar.coef)
attendance.model4$model          <- 'Model 4'
avoidable.model4$model           <- 'Model 4'
admissions.model4$model          <- 'Model 4'
length.of.stay.model4$model      <- 'Model 4'
case.fatality.model4$model       <- 'Model 4'
## ambulance.times.model4$model     <- 'Model 4'
results.model4 <-rbind(attendance.model4,
                       avoidable.model4,
                       admissions.model4,
                       length.of.stay.model4,
                       case.fatality.model4)
                       ## ambulance.times)
rm(attendance.model4,
   avoidable.model4,
   admissions.model4,
   length.of.stay.model4,
   case.fatality.model4)
## ambulance.times.model4)

## Model 5
attendance.model5 <- rbind(mode.of.arrival.any$model5.panelar.coef,
                           mode.of.arrival.other$model5.panelar.coef,
                           mode.of.arrival.ambulance$model5.panelar.coef,
                           unnecessary.attendance$model5.panelar.coef)
avoidable.model5 <- rbind(avoidable.emergency.admissions.any$model5.panelar.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model5.panelar.coef,
                          ## avoidable.emergency.admissions.angina$model5.panelar.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model5.panelar.coef,
                          ## avoidable.emergency.admissions.cellulitis$model5.panelar.coef,
                          ## avoidable.emergency.admissions.copd$model5.panelar.coef,
                          ## avoidable.emergency.admissions.dvt$model5.panelar.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model5.panelar.coef,
                          ## avoidable.emergency.admissions.falls$model5.panelar.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model5.panelar.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model5.panelar.coef,
                          avoidable.emergency.admissions.chest.pain$model5.panelar.coef)
                          ## avoidable.emergency.admissions.pyrexial.child$model5.panelar.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model5.panelar.coef)
admissions.model5 <- rbind(all.emergency.admissions.all$model5.panelar.coef,
                           ed.attendances.admitted.all$model5.panelar.coef,
                           ed.attendances.admitted.fraction.admitted$model5.panelar.coef,
                           ed.attendances.admitted.admitted$model5.panelar.coef,
                           critical.care.cips.all$model5.panelar.coef,
                           critical.care.cips.critical$model5.panelar.coef,
                           critical.care.cips.fraction$model5.panelar.coef)
length.of.stay.model5 <- rbind(length.of.stay.mean$model5.panelar.coef,
                               length.of.stay.median$model5.panelar.coef)
case.fatality.model5 <- rbind(case.fatality.ratio.any$model5.panelar.coef)
                              ## case.fatality.ratio.acute.heart.failure$model5.panelar.coef,
                              ## case.fatality.ratio.anaphylaxis$model5.panelar.coef,
                              ## case.fatality.ratio.asthma$model5.panelar.coef,
                              ## case.fatality.ratio.falls$model5.panelar.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model5.panelar.coef,
                              ## case.fatality.ratio.meningitis$model5.panelar.coef,
                              ## case.fatality.ratio.myocardial.infarction$model5.panelar.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model5.panelar.coef,
                              ## case.fatality.ratio.road.traffic.accident$model5.panelar.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model5.panelar.coef,
                              ## case.fatality.ratio.self.harm$model5.panelar.coef,
                              ## case.fatality.ratio.septic.shock$model5.panelar.coef,
                              ## case.fatality.ratio.serious.head.injury$model5.panelar.coef,
                              ## case.fatality.ratio.stroke.cva$model5.panelar.coef)
## ambulance.times.model5 <- rbind(ambulance.mean.times.call.to.dest$model5.panelar.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model5.panelar.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model5.panelar.coef,
                                   ## ambulance.mean.times.dest.to.clear$model5.panelar.coef,
                                   ## ambulance.mean.times.scene.to.dest$model5.panelar.coef)
attendance.model5$model          <- 'Model 5'
avoidable.model5$model           <- 'Model 5'
admissions.model5$model          <- 'Model 5'
length.of.stay.model5$model      <- 'Model 5'
case.fatality.model5$model       <- 'Model 5'
## ambulance.times.model5$model     <- 'Model 5'
results.model5 <-rbind(attendance.model5,
                       avoidable.model5,
                       admissions.model5,
                       length.of.stay.model5,
                       case.fatality.model5)
                       ## ambulance.times)
rm(attendance.model5,
   avoidable.model5,
   admissions.model5,
   length.of.stay.model5,
   case.fatality.model5)
## ambulance.times.model5)

## Model 6
attendance.model6 <- rbind(mode.of.arrival.any$model6.panelar.bishop.coef,
                                mode.of.arrival.any$model6.panelar.hartlepool.coef,
                                mode.of.arrival.any$model6.panelar.hemel.coef,
                                mode.of.arrival.any$model6.panelar.newark.coef,
                                mode.of.arrival.any$model6.panelar.rochdale.coef,
                                mode.of.arrival.other$model6.panelar.bishop.coef,
                                mode.of.arrival.other$model6.panelar.hartlepool.coef,
                                mode.of.arrival.other$model6.panelar.hemel.coef,
                                mode.of.arrival.other$model6.panelar.newark.coef,
                                mode.of.arrival.other$model6.panelar.rochdale.coef,
                                mode.of.arrival.ambulance$model6.panelar.bishop.coef,
                                mode.of.arrival.ambulance$model6.panelar.hartlepool.coef,
                                mode.of.arrival.ambulance$model6.panelar.hemel.coef,
                                mode.of.arrival.ambulance$model6.panelar.newark.coef,
                                mode.of.arrival.ambulance$model6.panelar.rochdale.coef,
                                unnecessary.attendance$model6.panelar.bishop.coef,
                                unnecessary.attendance$model6.panelar.hartlepool.coef,
                                unnecessary.attendance$model6.panelar.hemel.coef,
                                unnecessary.attendance$model6.panelar.newark.coef,
                                unnecessary.attendance$model6.panelar.rochdale.coef)
avoidable.model6 <- rbind(avoidable.emergency.admissions.any$model6.panelar.bishop.coef,
                          avoidable.emergency.admissions.any$model6.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.any$model6.panelar.hemel.coef,
                          avoidable.emergency.admissions.any$model6.panelar.newark.coef,
                          avoidable.emergency.admissions.any$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.angina$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.angina$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.angina$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.angina$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.angina$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.cellulitis$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.cellulitis$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.cellulitis$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.cellulitis$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.cellulitis$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.copd$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.copd$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.copd$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.copd$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.copd$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.dvt$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.dvt$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.dvt$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.dvt$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.dvt$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.falls$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.falls$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.falls$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.falls$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.falls$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model6.panelar.rochdale.coef,
                          avoidable.emergency.admissions.chest.pain$model6.panelar.bishop.coef,
                          avoidable.emergency.admissions.chest.pain$model6.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.chest.pain$model6.panelar.hemel.coef,
                          avoidable.emergency.admissions.chest.pain$model6.panelar.newark.coef,
                          avoidable.emergency.admissions.chest.pain$model6.panelar.rochdale.coef)
                          ## avoidable.emergency.admissions.pyrexial.child$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model6.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model6.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model6.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model6.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model6.panelar.newark.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model6.panelar.rochdale.coef)
admissions.model6 <- rbind(all.emergency.admissions.all$model6.panelar.bishop.coef,
                           all.emergency.admissions.all$model6.panelar.hartlepool.coef,
                           all.emergency.admissions.all$model6.panelar.hemel.coef,
                           all.emergency.admissions.all$model6.panelar.newark.coef,
                           all.emergency.admissions.all$model6.panelar.rochdale.coef,
                           ed.attendances.admitted.all$model6.panelar.bishop.coef,
                           ed.attendances.admitted.all$model6.panelar.hartlepool.coef,
                           ed.attendances.admitted.all$model6.panelar.hemel.coef,
                           ed.attendances.admitted.all$model6.panelar.newark.coef,
                           ed.attendances.admitted.all$model6.panelar.rochdale.coef,
                           ed.attendances.admitted.fraction.admitted$model6.panelar.bishop.coef,
                           ed.attendances.admitted.fraction.admitted$model6.panelar.hartlepool.coef,
                           ed.attendances.admitted.fraction.admitted$model6.panelar.hemel.coef,
                           ed.attendances.admitted.fraction.admitted$model6.panelar.newark.coef,
                           ed.attendances.admitted.fraction.admitted$model6.panelar.rochdale.coef,
                           ed.attendances.admitted.admitted$model6.panelar.bishop.coef,
                           ed.attendances.admitted.admitted$model6.panelar.hartlepool.coef,
                           ed.attendances.admitted.admitted$model6.panelar.hemel.coef,
                           ed.attendances.admitted.admitted$model6.panelar.newark.coef,
                           ed.attendances.admitted.admitted$model6.panelar.rochdale.coef,
                           critical.care.cips.all$model6.panelar.bishop.coef,
                           critical.care.cips.all$model6.panelar.hartlepool.coef,
                           critical.care.cips.all$model6.panelar.hemel.coef,
                           critical.care.cips.all$model6.panelar.newark.coef,
                           critical.care.cips.all$model6.panelar.rochdale.coef,
                           critical.care.cips.critical$model6.panelar.bishop.coef,
                           critical.care.cips.critical$model6.panelar.hartlepool.coef,
                           critical.care.cips.critical$model6.panelar.hemel.coef,
                           critical.care.cips.critical$model6.panelar.newark.coef,
                           critical.care.cips.critical$model6.panelar.rochdale.coef,
                           critical.care.cips.fraction$model6.panelar.bishop.coef,
                           critical.care.cips.fraction$model6.panelar.hartlepool.coef,
                           critical.care.cips.fraction$model6.panelar.hemel.coef,
                           critical.care.cips.fraction$model6.panelar.newark.coef,
                           critical.care.cips.fraction$model6.panelar.rochdale.coef)
length.of.stay.model6 <- rbind(length.of.stay.mean$model6.panelar.bishop.coef,
                               length.of.stay.mean$model6.panelar.hartlepool.coef,
                               length.of.stay.mean$model6.panelar.hemel.coef,
                               length.of.stay.mean$model6.panelar.newark.coef,
                               length.of.stay.mean$model6.panelar.rochdale.coef,
                               length.of.stay.median$model6.panelar.bishop.coef,
                               length.of.stay.median$model6.panelar.hartlepool.coef,
                               length.of.stay.median$model6.panelar.hemel.coef,
                               length.of.stay.median$model6.panelar.newark.coef,
                               length.of.stay.median$model6.panelar.rochdale.coef)
case.fatality.model6 <- rbind(case.fatality.ratio.any$model6.panelar.bishop.coef,
                              case.fatality.ratio.any$model6.panelar.hartlepool.coef,
                              case.fatality.ratio.any$model6.panelar.hemel.coef,
                              case.fatality.ratio.any$model6.panelar.newark.coef,
                              case.fatality.ratio.any$model6.panelar.rochdale.coef)
                              ## case.fatality.ratio.acute.heart.failure$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.acute.heart.failure$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.acute.heart.failure$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.acute.heart.failure$model6.panelar.newark.coef,
                              ## case.fatality.ratio.acute.heart.failure$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.anaphylaxis$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.anaphylaxis$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.anaphylaxis$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.anaphylaxis$model6.panelar.newark.coef,
                              ## case.fatality.ratio.anaphylaxis$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.asthma$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.asthma$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.asthma$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.asthma$model6.panelar.newark.coef,
                              ## case.fatality.ratio.asthma$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.falls$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.falls$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.falls$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.falls$model6.panelar.newark.coef,
                              ## case.fatality.ratio.falls$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model6.panelar.newark.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.meningitis$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.meningitis$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.meningitis$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.meningitis$model6.panelar.newark.coef,
                              ## case.fatality.ratio.meningitis$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.myocardial.infarction$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.myocardial.infarction$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.myocardial.infarction$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.myocardial.infarction$model6.panelar.newark.coef,
                              ## case.fatality.ratio.myocardial.infarction$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model6.panelar.newark.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.road.traffic.accident$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.road.traffic.accident$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.road.traffic.accident$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.road.traffic.accident$model6.panelar.newark.coef,
                              ## case.fatality.ratio.road.traffic.accident$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model6.panelar.newark.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.self.harm$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.self.harm$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.self.harm$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.self.harm$model6.panelar.newark.coef,
                              ## case.fatality.ratio.self.harm$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.septic.shock$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.septic.shock$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.septic.shock$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.septic.shock$model6.panelar.newark.coef,
                              ## case.fatality.ratio.septic.shock$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.serious.head.injury$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.serious.head.injury$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.serious.head.injury$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.serious.head.injury$model6.panelar.newark.coef,
                              ## case.fatality.ratio.serious.head.injury$model6.panelar.rochdale.coef,
                              ## case.fatality.ratio.stroke.cva$model6.panelar.bishop.coef,
                              ## case.fatality.ratio.stroke.cva$model6.panelar.hartlepool.coef,
                              ## case.fatality.ratio.stroke.cva$model6.panelar.hemel.coef,
                              ## case.fatality.ratio.stroke.cva$model6.panelar.newark.coef,
                              ## case.fatality.ratio.stroke.cva$model6.panelar.rochdale.coef)
## ambulance.times.model6 <- rbind(ambulance.mean.times.call.to.dest$model6.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.dest$model6.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.dest$model6.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.dest$model6.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.dest$model6.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model6.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model6.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model6.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model6.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model6.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model6.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model6.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model6.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model6.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model6.panelar.rochdale.coef,
                                   ## ambulance.mean.times.dest.to.clear$model6.panelar.bishop.coef,
                                   ## ambulance.mean.times.dest.to.clear$model6.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.dest.to.clear$model6.panelar.hemel.coef,
                                   ## ambulance.mean.times.dest.to.clear$model6.panelar.newark.coef,
                                   ## ambulance.mean.times.dest.to.clear$model6.panelar.rochdale.coef,
                                   ## ambulance.mean.times.scene.to.dest$model6.panelar.bishop.coef,
                                   ## ambulance.mean.times.scene.to.dest$model6.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.scene.to.dest$model6.panelar.hemel.coef,
                                   ## ambulance.mean.times.scene.to.dest$model6.panelar.newark.coef,
                                   ## ambulance.mean.times.scene.to.dest$model6.panelar.rochdale.coef)
attendance.model6$model          <- 'Model 6'
avoidable.model6$model           <- 'Model 6'
admissions.model6$model          <- 'Model 6'
length.of.stay.model6$model      <- 'Model 6'
case.fatality.model6$model       <- 'Model 6'
## ambulance.times.model6$model     <- 'Model 6'
results.model6 <-rbind(attendance.model6,
                       avoidable.model6,
                       admissions.model6,
                       length.of.stay.model6,
                       case.fatality.model6)
                       ## ambulance.times)
rm(attendance.model6,
   avoidable.model6,
   admissions.model6,
   length.of.stay.model6,
   case.fatality.model6)
## ambulance.times.model6)

## Model 7
attendance.model7 <- rbind(mode.of.arrival.any$model7.panelar.coef,
                           mode.of.arrival.other$model7.panelar.coef,
                           mode.of.arrival.ambulance$model7.panelar.coef,
                           unnecessary.attendance$model7.panelar.coef)
avoidable.model7 <- rbind(avoidable.emergency.admissions.any$model7.panelar.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model7.panelar.coef,
                          ## avoidable.emergency.admissions.angina$model7.panelar.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model7.panelar.coef,
                          ## avoidable.emergency.admissions.cellulitis$model7.panelar.coef,
                          ## avoidable.emergency.admissions.copd$model7.panelar.coef,
                          ## avoidable.emergency.admissions.dvt$model7.panelar.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model7.panelar.coef,
                          ## avoidable.emergency.admissions.falls$model7.panelar.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model7.panelar.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model7.panelar.coef,
                          avoidable.emergency.admissions.chest.pain$model7.panelar.coef)
                          ## avoidable.emergency.admissions.pyrexial.child$model7.panelar.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model7.panelar.coef)
admissions.model7 <- rbind(all.emergency.admissions.all$model7.panelar.coef,
                           ed.attendances.admitted.all$model7.panelar.coef,
                           ed.attendances.admitted.fraction.admitted$model7.panelar.coef,
                           ed.attendances.admitted.admitted$model7.panelar.coef,
                           critical.care.cips.all$model7.panelar.coef,
                           critical.care.cips.critical$model7.panelar.coef,
                           critical.care.cips.fraction$model7.panelar.coef)
length.of.stay.model7 <- rbind(length.of.stay.mean$model7.panelar.coef,
                               length.of.stay.median$model7.panelar.coef)
case.fatality.model7 <- rbind(case.fatality.ratio.any$model7.panelar.coef)
                              ## case.fatality.ratio.acute.heart.failure$model7.panelar.coef,
                              ## case.fatality.ratio.anaphylaxis$model7.panelar.coef,
                              ## case.fatality.ratio.asthma$model7.panelar.coef,
                              ## case.fatality.ratio.falls$model7.panelar.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model7.panelar.coef,
                              ## case.fatality.ratio.meningitis$model7.panelar.coef,
                              ## case.fatality.ratio.myocardial.infarction$model7.panelar.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model7.panelar.coef,
                              ## case.fatality.ratio.road.traffic.accident$model7.panelar.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model7.panelar.coef,
                              ## case.fatality.ratio.self.harm$model7.panelar.coef,
                              ## case.fatality.ratio.septic.shock$model7.panelar.coef,
                              ## case.fatality.ratio.serious.head.injury$model7.panelar.coef,
                              ## case.fatality.ratio.stroke.cva$model7.panelar.coef)
## ambulance.times.model7 <- rbind(ambulance.mean.times.call.to.dest$model7.panelar.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model7.panelar.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model7.panelar.coef,
                                   ## ambulance.mean.times.dest.to.clear$model7.panelar.coef,
                                   ## ambulance.mean.times.scene.to.dest$model7.panelar.coef)
attendance.model7$model          <- 'Model 7'
avoidable.model7$model           <- 'Model 7'
admissions.model7$model          <- 'Model 7'
length.of.stay.model7$model      <- 'Model 7'
case.fatality.model7$model       <- 'Model 7'
## ambulance.times.model7$model     <- 'Model 7'
results.model7 <-rbind(attendance.model7,
                       avoidable.model7,
                       admissions.model7,
                       length.of.stay.model7,
                       case.fatality.model7)
                       ## ambulance.times)
rm(attendance.model7,
   avoidable.model7,
   admissions.model7,
   length.of.stay.model7,
   case.fatality.model7)
## ambulance.times.model7)

## Model 8
attendance.model8 <- rbind(mode.of.arrival.any$model8.panelar.bishop.coef,
                                mode.of.arrival.any$model8.panelar.hartlepool.coef,
                                mode.of.arrival.any$model8.panelar.hemel.coef,
                                mode.of.arrival.any$model8.panelar.newark.coef,
                                mode.of.arrival.any$model8.panelar.rochdale.coef,
                                mode.of.arrival.other$model8.panelar.bishop.coef,
                                mode.of.arrival.other$model8.panelar.hartlepool.coef,
                                mode.of.arrival.other$model8.panelar.hemel.coef,
                                mode.of.arrival.other$model8.panelar.newark.coef,
                                mode.of.arrival.other$model8.panelar.rochdale.coef,
                                mode.of.arrival.ambulance$model8.panelar.bishop.coef,
                                mode.of.arrival.ambulance$model8.panelar.hartlepool.coef,
                                mode.of.arrival.ambulance$model8.panelar.hemel.coef,
                                mode.of.arrival.ambulance$model8.panelar.newark.coef,
                                mode.of.arrival.ambulance$model8.panelar.rochdale.coef,
                                unnecessary.attendance$model8.panelar.bishop.coef,
                                unnecessary.attendance$model8.panelar.hartlepool.coef,
                                unnecessary.attendance$model8.panelar.hemel.coef,
                                unnecessary.attendance$model8.panelar.newark.coef,
                                unnecessary.attendance$model8.panelar.rochdale.coef)
avoidable.model8 <- rbind(avoidable.emergency.admissions.any$model8.panelar.bishop.coef,
                          avoidable.emergency.admissions.any$model8.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.any$model8.panelar.hemel.coef,
                          avoidable.emergency.admissions.any$model8.panelar.newark.coef,
                          avoidable.emergency.admissions.any$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.acute.mental.health.crisis$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.angina$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.angina$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.angina$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.angina$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.angina$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.blocked.catheter$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.cellulitis$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.cellulitis$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.cellulitis$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.cellulitis$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.cellulitis$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.copd$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.copd$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.copd$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.copd$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.copd$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.dvt$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.dvt$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.dvt$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.dvt$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.dvt$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.epileptic.fit$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.falls$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.falls$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.falls$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.falls$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.falls$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.hypoglycaemia$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.minor.head.injuries$model8.panelar.rochdale.coef,
                          avoidable.emergency.admissions.chest.pain$model8.panelar.bishop.coef,
                          avoidable.emergency.admissions.chest.pain$model8.panelar.hartlepool.coef,
                          avoidable.emergency.admissions.chest.pain$model8.panelar.hemel.coef,
                          avoidable.emergency.admissions.chest.pain$model8.panelar.newark.coef,
                          avoidable.emergency.admissions.chest.pain$model8.panelar.rochdale.coef)
                          ## avoidable.emergency.admissions.pyrexial.child$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.pyrexial.child$model8.panelar.rochdale.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model8.panelar.bishop.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model8.panelar.hartlepool.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model8.panelar.hemel.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model8.panelar.newark.coef,
                          ## avoidable.emergency.admissions.urinary.tract.infection$model8.panelar.rochdale.coef)
admissions.model8 <- rbind(all.emergency.admissions.all$model8.panelar.bishop.coef,
                           all.emergency.admissions.all$model8.panelar.hartlepool.coef,
                           all.emergency.admissions.all$model8.panelar.hemel.coef,
                           all.emergency.admissions.all$model8.panelar.newark.coef,
                           all.emergency.admissions.all$model8.panelar.rochdale.coef,
                           ed.attendances.admitted.all$model8.panelar.bishop.coef,
                           ed.attendances.admitted.all$model8.panelar.hartlepool.coef,
                           ed.attendances.admitted.all$model8.panelar.hemel.coef,
                           ed.attendances.admitted.all$model8.panelar.newark.coef,
                           ed.attendances.admitted.all$model8.panelar.rochdale.coef,
                           ed.attendances.admitted.fraction.admitted$model8.panelar.bishop.coef,
                           ed.attendances.admitted.fraction.admitted$model8.panelar.hartlepool.coef,
                           ed.attendances.admitted.fraction.admitted$model8.panelar.hemel.coef,
                           ed.attendances.admitted.fraction.admitted$model8.panelar.newark.coef,
                           ed.attendances.admitted.fraction.admitted$model8.panelar.rochdale.coef,
                           ed.attendances.admitted.admitted$model8.panelar.bishop.coef,
                           ed.attendances.admitted.admitted$model8.panelar.hartlepool.coef,
                           ed.attendances.admitted.admitted$model8.panelar.hemel.coef,
                           ed.attendances.admitted.admitted$model8.panelar.newark.coef,
                           ed.attendances.admitted.admitted$model8.panelar.rochdale.coef,
                           critical.care.cips.all$model8.panelar.bishop.coef,
                           critical.care.cips.all$model8.panelar.hartlepool.coef,
                           critical.care.cips.all$model8.panelar.hemel.coef,
                           critical.care.cips.all$model8.panelar.newark.coef,
                           critical.care.cips.all$model8.panelar.rochdale.coef,
                           critical.care.cips.critical$model8.panelar.bishop.coef,
                           critical.care.cips.critical$model8.panelar.hartlepool.coef,
                           critical.care.cips.critical$model8.panelar.hemel.coef,
                           critical.care.cips.critical$model8.panelar.newark.coef,
                           critical.care.cips.critical$model8.panelar.rochdale.coef,
                           critical.care.cips.fraction$model8.panelar.bishop.coef,
                           critical.care.cips.fraction$model8.panelar.hartlepool.coef,
                           critical.care.cips.fraction$model8.panelar.hemel.coef,
                           critical.care.cips.fraction$model8.panelar.newark.coef,
                           critical.care.cips.fraction$model8.panelar.rochdale.coef)
length.of.stay.model8 <- rbind(length.of.stay.mean$model8.panelar.bishop.coef,
                               length.of.stay.mean$model8.panelar.hartlepool.coef,
                               length.of.stay.mean$model8.panelar.hemel.coef,
                               length.of.stay.mean$model8.panelar.newark.coef,
                               length.of.stay.mean$model8.panelar.rochdale.coef,
                               length.of.stay.median$model8.panelar.bishop.coef,
                               length.of.stay.median$model8.panelar.hartlepool.coef,
                               length.of.stay.median$model8.panelar.hemel.coef,
                               length.of.stay.median$model8.panelar.newark.coef,
                               length.of.stay.median$model8.panelar.rochdale.coef)
case.fatality.model8 <- rbind(case.fatality.ratio.any$model8.panelar.bishop.coef,
                              case.fatality.ratio.any$model8.panelar.hartlepool.coef,
                              case.fatality.ratio.any$model8.panelar.hemel.coef,
                              case.fatality.ratio.any$model8.panelar.newark.coef,
                              case.fatality.ratio.any$model8.panelar.rochdale.coef)
                              ## case.fatality.ratio.acute.heart.failure$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.acute.heart.failure$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.acute.heart.failure$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.acute.heart.failure$model8.panelar.newark.coef,
                              ## case.fatality.ratio.acute.heart.failure$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.anaphylaxis$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.anaphylaxis$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.anaphylaxis$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.anaphylaxis$model8.panelar.newark.coef,
                              ## case.fatality.ratio.anaphylaxis$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.asthma$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.asthma$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.asthma$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.asthma$model8.panelar.newark.coef,
                              ## case.fatality.ratio.asthma$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.falls$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.falls$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.falls$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.falls$model8.panelar.newark.coef,
                              ## case.fatality.ratio.falls$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model8.panelar.newark.coef,
                              ## case.fatality.ratio.fractured.neck.of.femur$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.meningitis$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.meningitis$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.meningitis$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.meningitis$model8.panelar.newark.coef,
                              ## case.fatality.ratio.meningitis$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.myocardial.infarction$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.myocardial.infarction$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.myocardial.infarction$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.myocardial.infarction$model8.panelar.newark.coef,
                              ## case.fatality.ratio.myocardial.infarction$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model8.panelar.newark.coef,
                              ## case.fatality.ratio.pregnancy.and.birth.related$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.road.traffic.accident$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.road.traffic.accident$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.road.traffic.accident$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.road.traffic.accident$model8.panelar.newark.coef,
                              ## case.fatality.ratio.road.traffic.accident$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model8.panelar.newark.coef,
                              ## case.fatality.ratio.ruptured.aortic.aneurysm$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.self.harm$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.self.harm$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.self.harm$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.self.harm$model8.panelar.newark.coef,
                              ## case.fatality.ratio.self.harm$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.septic.shock$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.septic.shock$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.septic.shock$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.septic.shock$model8.panelar.newark.coef,
                              ## case.fatality.ratio.septic.shock$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.serious.head.injury$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.serious.head.injury$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.serious.head.injury$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.serious.head.injury$model8.panelar.newark.coef,
                              ## case.fatality.ratio.serious.head.injury$model8.panelar.rochdale.coef,
                              ## case.fatality.ratio.stroke.cva$model8.panelar.bishop.coef,
                              ## case.fatality.ratio.stroke.cva$model8.panelar.hartlepool.coef,
                              ## case.fatality.ratio.stroke.cva$model8.panelar.hemel.coef,
                              ## case.fatality.ratio.stroke.cva$model8.panelar.newark.coef,
                              ## case.fatality.ratio.stroke.cva$model8.panelar.rochdale.coef)
## ambulance.times.model8 <- rbind(ambulance.mean.times.call.to.dest$model8.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.dest$model8.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.dest$model8.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.dest$model8.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.dest$model8.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model8.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model8.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model8.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model8.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.any$model8.panelar.rochdale.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model8.panelar.bishop.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model8.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model8.panelar.hemel.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model8.panelar.newark.coef,
                                   ## ambulance.mean.times.call.to.scene.conveying$model8.panelar.rochdale.coef,
                                   ## ambulance.mean.times.dest.to.clear$model8.panelar.bishop.coef,
                                   ## ambulance.mean.times.dest.to.clear$model8.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.dest.to.clear$model8.panelar.hemel.coef,
                                   ## ambulance.mean.times.dest.to.clear$model8.panelar.newark.coef,
                                   ## ambulance.mean.times.dest.to.clear$model8.panelar.rochdale.coef,
                                   ## ambulance.mean.times.scene.to.dest$model8.panelar.bishop.coef,
                                   ## ambulance.mean.times.scene.to.dest$model8.panelar.hartlepool.coef,
                                   ## ambulance.mean.times.scene.to.dest$model8.panelar.hemel.coef,
                                   ## ambulance.mean.times.scene.to.dest$model8.panelar.newark.coef,
                                   ## ambulance.mean.times.scene.to.dest$model8.panelar.rochdale.coef)
attendance.model8$model          <- 'Model 8'
avoidable.model8$model           <- 'Model 8'
admissions.model8$model          <- 'Model 8'
length.of.stay.model8$model      <- 'Model 8'
case.fatality.model8$model       <- 'Model 8'
## ambulance.times.model8$model     <- 'Model 8'
results.model8 <-rbind(attendance.model8,
                       avoidable.model8,
                       admissions.model8,
                       length.of.stay.model8,
                       case.fatality.model8)
                       ## ambulance.times)
rm(attendance.model8,
   avoidable.model8,
   admissions.model8,
   length.of.stay.model8,
   case.fatality.model8)
## ambulance.times.model8)

## Bind all the results together
results <- rbind(results.model1,
                 results.model2,
                 results.model3,
                 results.model4,
                 results.model5,
                 results.model6,
                 results.model7,
                 results.model8)
rm(results.model1,
   results.model2,
   results.model3,
   results.model4,
   results.model5,
   results.model6,
   results.model7,
   results.model8)

## Filter the intervention
closure <- filter(results, term == 'closure')

## Make a table of results

```
```{r regression_summary_table_print, echo = FALSE, cache = FALSE, results = 'hide', eval = FALSE}
## Now print the resulting table

```
