## Potentiall Avoidable Emergency Admissions (Matched Controls)


### Bishop Auckland General Hospital
```{r bishop_unnecessary_admissions_matched_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = TRUE}
bishop.unnecessary.admissions.matched$ts.plot.events
```

```{r bishop_unnecessary_admissions_matched_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = TRUE}
bishop.unnecessary.admissions.matched$panelar %>% summary()
```


### Hemel Hempstead Hospital
```{r hemel_unnecessary_admissions_matched_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = TRUE}
hemel.unnecessary.admissions.matched$ts.plot.events
```

```{r hemel_unnecessary_admissions_matched_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = TRUE}
hemel.unnecessary.admissions.matched$panelar %>% summary()
```


### Newark Hospital
```{r newark_unnecessary_admissions_matched_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = TRUE}
newark.unnecessary.admissions.matched$ts.plot.events
```

```{r newark_unnecessary_admissions_matched_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = TRUE}
newark.unnecessary.admissions.matched$panelar %>% summary()
```

### Rochdale Infirmary
```{r rochdale_unnecessary_admissions_matched_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = TRUE}
rochdale.unnecessary.admissions.matched$ts.plot.events
```

```{r rochdale_unnecessary_admissions_matched_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = TRUE}
rochdale.unnecessary.admissions.matched$panelar %>% summary()
```


### University Hospital of Hartlepool
```{r hartlepool_unnecessary_admissions_matched_plot, echo = FALSE, cache = FALSE, results = 'asis', eval = TRUE}
hartlepool.unnecessary.admissions.matched$ts.plot.events
```
```{r hartlepool_unnecessary_admissions_matched_panelar, echo = FALSE, cache = FALSE, results = 'markup', eval = TRUE}
hartlepool.unnecessary.admissions.matched$panelar %>% summary()
```




```{r echo = FALSE, cache = FALSE, eval = FALSE}
rm(unnecessary_ed_attendances_measure,
   bishop.unnecessary.admissions.matched,
   hemel.unnecessary.admissions.matched,
   newark.unnecessary.admissions.matched,
   rochdale.unnecessary.admissions.matched,
   hartlepool.unnecessary.admissions.matched)
```
