```{r echo = FALSE, cache = FALSE, eval = TRUE}
load('d:/Rpackages/rclosed/data/avoidable emergency admissions measure.Rda')
```
```{r bishop_unnecessary_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
bishop.unnecessary.admissions.matched <- closed_regress(df            = avoidable_emergency_admissions_measure,
                                                        df.steps      = sites,
	                                                site          = 'Bishop Auckland General Hospital',
                                                        controls      = 'matched control',
                                                        indicator     = 'avoidable emergency admissions',
                         covariates    = c('time.to.ed', 'town'),
                         steps         = c('closure'),
                                                        sub.indicator = 'any',
                                                        fit.with      = 'both',
                                                        plot          = TRUE,
                                                        common.y      = TRUE,
                                                        theme         = theme_bw(),
                                                        latex         = FALSE,
                                                        html          = FALSE)
```
```{r hemel_unnecessary_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hemel.unnecessary.admissions.matched <- closed_regress(df            = avoidable_emergency_admissions_measure,
                                                       df.steps      = sites,
                                                       site          = 'Hemel Hempstead Hospital',
                                                       controls      = 'matched control',
                                                       indicator     = 'avoidable emergency admissions',
                                                       covariates    = c('time.to.ed', 'town'),
                                                       steps         = c('closure'),
                                                       sub.indicator = 'any',
                                                       fit.with      = 'both',
                                                       plot          = TRUE,
                                                       common.y      = TRUE,
                                                       theme         = theme_bw(),
                                                       latex         = FALSE,
                                                       html          = FALSE)
```
```{r newark_unnecessary_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
newark.unnecessary.admissions.matched <- closed_regress(df            = avoidable_emergency_admissions_measure,
                                                        df.steps      = sites,
                                                        site          = 'Newark Hospital',
                                                        controls      = 'matched control',
                                                        indicator     = 'avoidable emergency admissions',
                                                        covariates    = c('time.to.ed', 'town'),
                                                        steps         = c('closure'),
                                                        sub.indicator = 'any',
                                                        fit.with      = 'both',
                                                        plot          = TRUE,
                                                        common.y      = TRUE,
                                                        theme         = theme_bw(),
                                                        latex         = FALSE,
                                                        html          = FALSE)
```
```{r rochdale_unnecessary_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
rochdale.unnecessary.admissions.matched <- closed_regress(df            = avoidable_emergency_admissions_measure,
                                                          df.steps      = sites,
		                                          site          = 'Rochdale Infirmary',
                                                          controls      = 'matched control',
                                                          indicator     = 'avoidable emergency admissions',
                                                          covariates    = c('time.to.ed', 'town'),
                                                          steps         = c('closure'),
                                                          sub.indicator = 'any',
                                                          fit.with      = 'both',
                                                          plot          = TRUE,
                                                          common.y      = TRUE,
                                                          theme         = theme_bw(),
                                                          latex         = FALSE,
                                                          html          = FALSE)
```
```{r hartlepool_unnecessary_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
hartlepool.unnecessary.admissions.matched <- closed_regress(df            = avoidable_emergency_admissions_measure,
					                    df.steps      = sites,
		                                            site          = 'University Hospital of Hartlepool',
                                                            controls      = 'matched control',
                                                            indicator     = 'avoidable emergency admissions',
                                                            covariates    = c('time.to.ed', 'town'),
                                                            steps         = c('closure'),
                                                            sub.indicator = 'any',
                                                            fit.with      = 'both',
                                                            plot          = TRUE,
                                                            common.y      = TRUE,
                                                            theme         = theme_bw(),
                                                            latex         = FALSE,
                                                            html          = FALSE)
```
```{r all_unnecessary_admissions_matched, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
all.unnecessary.admissions.matched <- closed_regress(df            = avoidable_emergency_admissions_measure,
					             df.steps      = sites,
		                                     site          = 'All',
                                                     controls      = 'matched control',
                                                     indicator     = 'avoidable emergency admissions',
                                                     covariates    = c(''),
                                                     steps         = c('closure'),
                                                     sub.indicator = 'any',
                                                     fit.with      = 'both',
                                                     plot          = TRUE,
                                                     common.y      = TRUE,
                                                     theme         = theme_bw(),
                                                     latex         = FALSE,
                                                     html          = FALSE)
```
```{r all_unnecessary_admissions_pooled, echo = FALSE, cache = FALSE, results = 'hide', eval = FALSE}
all.unnecessary.admissions.pooled <- closed_regress(df            = avoidable_emergency_admissions_measure,
					            df.steps      = sites,
		                                    site          = 'All',
                                                    controls      = 'pooled control',
                                                    indicator     = 'avoidable emergency admissions',
                                                    covariates    = c(''),
                                                    steps         = c('closure'),
                                                    sub.indicator = 'any',
                                                    fit.with      = 'both',
                                                    plot          = TRUE,
                                                    common.y      = TRUE,
                                                    theme         = theme_bw(),
                                                    latex         = FALSE,
                                                    html          = FALSE)
```
```{r echo = FALSE, cache = FALSE, eval = TRUE}
## Save results for subsequent loading
save(bishop.unnecessary.admissions.matched,
     hemel.unnecessary.admissions.matched,
     newark.unnecessary.admissions.matched,
     rochdale.unnecessary.admissions.matched,
     hartlepool.unnecessary.admissions.matched,
     all.unnecessary.admissions.matched,
#     all.unnecessary.admissions.pooled,
     file = '../lib/data/unnecessary_ed_admissions.RData')
rm(avoidable_emergency_admissions_measure)
```
