shinyUI(
    fluidPage(
        titlePanel("Hubble - Comparison of RBL and HAL",
                   p('Welcome, you are viewing the results of the ClosED study which seeks to investigate the impact of closing Emergency Departments on local population health.  You can modify which results you can view on each of the tabs using the menus.'),),
        ## sidebarPanel(width = 4,
        ##              selectInput('hubble',
        ##                          'Choose how to plot and summarise the data :',
        ##                          choices = c('All',
        ##                                      'By Center',
        ##                                      'By Surgeon'),
        ##                          multiple = FALSE)
        ##              ),
        sidebarPanel(width = 4,
                     h2('Options...'),
                     selectInput('hospital',
                                 'Hospital of Interest',
                                 choices = c('Bishop Auckland'  = 'bishop',
                                             'Hartlepool'       = 'hartlepool',
                                             'Hemel Hempstead'  = 'hemel',
                                             'Newark'           = 'newark',
                                             'Rochdale'         = 'rochdale',
                                             'All'              = 'all'),
                                 selected = 'all',
                                 multiple = TRUE),
                     p('Select which events to display for each outcome...'),
                     selectInput('mortality',
                                 'Mortality',
                                 choices  = c('Acute Heart Failure'                     = 'ahf',
                                              'Anaphalaxis'                             = 'anaphalaxis',
                                              'Asthma'                                  = 'asthma',
                                              'Cardiac Arrest'                          = 'ca',
                                              'Falls in those < 75'                     = 'falls',
                                              'Fractured Neck of Femur'                 = 'femur',
                                              'Meningitis'                              = 'meningitis',
                                              'Myocradial Infarction'                   = 'mi',
                                              'Non-superficial Head Injuries'           = 'head',
                                              'Pregnancy and Birth Related Conditions'  = 'pregnancy',
                                              'Road Traffic Accidents'                  = 'rta',
                                              'Ruptured Aurtic Aneuyrsm'                = 'aneurysm',
                                              'Self-harm'                               = 'selfharm',
                                              'Septic Shock'                            = 'septicshock',
                                              'Stroke/CVA'                              = 'stroke'),
                                 selected = 'mi',
                                 multiple = FALSE),
                     selectInput('mortality',
                                 'Mortality',
                                 choices  = c('Acute Mental Crisis'                    = 'mentalcrisis',
                                              'Angina'                                 = 'angina',
                                              'Blocked Urinary Catheter'               = 'urinarycatheter',
                                              'Cellulitis'                             = 'cellulitis',
                                              'Childhood Pyrexial'                     = 'pyrexial',
                                              'Chronic Obstructive Pulmonary Disease'  = 'copd',
                                              'Deep Vein Thrombosis'                   = 'dvt',
                                              'Epileptic Seizure'                      = 'seizure',
                                              'Falls in those > 75'                    = 'falls',
                                              'Hypoglycemia'                           = 'hypoglycemia',
                                              'Non-specific Abdominal Pains'           = 'abdominalpains',
                                              'Non-specific Chest Pains'               = 'chestpaints',
                                              'Superficial Head Injuries'              = 'head',
                                              'Urinary Tract Infections'               = 'uti'),
                                 selected = 'mi',
                                 multiple = FALSE),
                     sliderInput('digits',
                                 'Decimal Places',
                                 min   = 1,
                                 max   = 5,
                                 value = 2),
                     ),
        mainPanel(width = 8,
                  height = 16,
                  column(12,
                         tabsetPanel(tabPanel("Mortality"
                                              column(6,
                                                     h2('Mortality Rate')),
                                              column(6,
                                                     h2('Case Fatality Ratio'))
                                              ),
                                     tabPanel("Emergency Attendance",
                                              column(3,
                                                     h2('Overall')),
                                              column(3,
                                                     h2('Ambulance and "Other"')),
                                              column(3,
                                                     h2('Discharges without Treatment')),
                                              column(3,
                                                     h2('Resulting in Admission'))
                                              ),
                                     tabPanel("Emergency Admissions",
                                              column(6,
                                                     h2('Overall')),
                                              column(6,
                                                     h2('Urgent Conditions'))
                                              ),
                                     tabPanel("Condition Severity",
                                              column(6,
                                                     h2('Mean Length of Stay')),
                                              column(6,
                                                     h2('Proportion Admitted to Critical Care'))
                                              ),
                                     tabPanel("Ambulance Service (Time Time from...)",
                                              column(3,
                                                     h2('999 Call to Scene')),
                                              column(3,
                                                     h2('Scene to Hospital')),
                                              column(3,
                                                     h2('999 Call to Hospital')),
                                              column(3,
                                                     h2('Arriving at Hospital to "Clear"'))
                                              ),
                                     tabPanel("Summary Statistics",
                                              column(6,
                                                     h2('Autocorrelation')),
                                              column(6,
                                                     h2('Time Series'))
                                              ),
                                     tabPanel("ToDo",
                                              column(6,
                                              fluidRow(p("Some of the things not yet working or that I would like to implement..."),
                                                       HTML("<ul>
                                                              <li> Data in summary counts by month for each outcome and by each method of allocating to LSOA.
                                                              <li> Write functions for plotting data (unadjusted and adjusted i.e. smoothing for seasonal variation).
                                                              <li> Calculate Auto-correlation.
                                                              <li> Regression objects from Prais-Winsten to be recognised by Stargazer package to ease formatting of results.
                                                            </ul>"))
                                                     )
                                              )
                                     )
                         )
                  )
    )
)
