Methods are described in detail in the Statistical Analysis Plan which can be viewed [online](https://www.overleaf.com/read/ffzknqdcjkpw).  Once the page has loaded click on PDF at the top of the page to download a PDF copy.  Briefly though the study seeks to investigate via interuptted time-series analysis whether closing Accident and Emergency departments impacts on any of a host of pre-selected indicators of the quality of health care provision[@knotopantelis2015;@penfold2013].  [Prais-Winsten regression](https://en.wikipedia.org/wiki/Prais%E2%80%93Winsten_estimation)[@prais1954] is utilised to account for auto-correlation between sequential measurements over time.  Broadly the approach taken is that of @turner2013.

### Models

Seven models are tested sequentially with growing complexity and are detailed below.

Table: Models tested in ClosED

Model  | Case Site    | Control Site         | Panel | Covariates
-------|--------------|----------------------|-------|----------------------------------------
1      | Individual   | None                 | ED    | season + time + closure + nhs111 + other.centre + ambulance.diversion
2      | Individual   | Primary Matched      | ED    | season + time + closure * site + nhs111 + other.centre + ambulance.diversion
3.1    | Individual   | All Matched          | ED    | season + time + closure * pooled.site + site + nhs111 + other.centre + ambulance.diversion
3.2    | Individual   | All Matched (Pooled) | ED  | season + time + closure * pooled.site + nhs111 + other.centre + ambulance.diversion
4      | All          | Primary Matched      | ED    | season + time + closure * site + nhs111 + other.centre + ambulance.diversion
5      | All          | All Matched          | ED    | season + time + closure * site + nhs111 + other.centre + ambulance.diversion
6.1    | Individual   | None                 | LSOA  | season + time + site + nhs111 + other.centre + ambulance.diversion + change in ED time
6.2    | Individual   | Primary Matched      | LSOA  | season + time + site + nhs111 + other.centre + ambulance.diversion + change in ED time
7.1    | All          | None                 | LSOA  | season + time + site + nhs111 + other.centre + ambulance.diversion + change in ED time
7.2    | All          | Primary Matched      | LSOA  | season + time + site + nhs111 + other.centre + ambulance.diversion + change in ED time


**NB** - Model 3.2 is now included after the Project Advisoty Group Meeting held 2016-07-04 which suggested that pooling control sites could be one approach.  The advisory statistician (Alex Bottle), advised when asked if such a model would be preferable, that it could certainly be investigated, but only after careful consideration of the results of Models 3.1 and 5 where sites are considered individually.  Subsequently àt a project meeting on 2016-07-08 [Jon Nicholl](mailto:j.nicholl@sheffield.ac.uk) inidcated that Model 3 should be modified to interact the same pooled dummy variable (`pooled.site`) with the dummy variable for (`closure`).

#### Indicators

A number of indicators have been pre-selected for investigation of the impact of closing Emergency Departments and are detailed below.

Indicators of Emergency Department closure adversely affecting local populations. Data Sources are **ONS** : ONS Mortality Data; **HES-ONS** : HES-ONS linked mortality data; **HES-AE** : HES A\&E attendance; **HES-APC** : HES Admitted Patient Care; AS : Ambulance Service CAD data. **NB** Ambulance 'clear' time is when an ambulance is available for their next job.

| Indicator  | Description | Data Source
|------------|-------------|---------------
| **Deaths** | Mortality rate for deaths occurring upto 3 days for 16 conditions (see table Avoidable Deaths | ONS / HES-ONS|
| **Risk of Death** | Case fatality ratio (deaths / cases) for the 16 serious conditions (see table Avoidable Deaths). | ONS / HES-ONS|
| **Emergency Attendance** | Total Type 1 ED Attendances for residents in the catchment area with any condition. | HES-AE |
|                          | Total Type 1 ED Attendances for residents in the catchment area arriving via Ambulance | HES-AE |
|                          | Total Type 1 ED Attendances for residents in the catchment area arriving via 'walk-in' mode. | HES-AE |
|                          | Arrivals at ED for residents in the catchment area who are discharged without treatment/investigation that utilised hospital facilities. | HES-AE |
|                          | Proportion of ED attendances for residents in the catchment area that resulted in admission to hospital bed. | HES-AE |
| **Emergency Admissions** | Number of emergency hospital admissions with any condition. | HES-APC |
|                          | Number of emergency hospital admissions for each of the 14 urgent conditions(table~\ref{avoidable-deaths}). | HES-APC |
|                          | These will be performed for all hospital admissions and then restricted to admissions where patients are resident in the catchment area.  | |
| **Condition Severity**   | For emergency admissions the mean length of stay. | HES-APC |
|                          | For emergency admissions the proportion admitted to critical care. | HES-APC |
| **Ambulance Service Performance** | Mean time from 999 call to ambulance arriving on scene. | AS |
|                                   | Mean time from ambulance arriving on scene to arriving at hospital. | AS |
|                                   | Mean time from 999 call to arriving at hospital. | AS |
|                                   | Mean time from ambulance arriving at hospital to 'clear' time. | AS |
|                                   | Total call volumes.    | AS |
|                                   |  Non-conveyance rates. | AS |

##### Avoidable Emergency Admissions and Avoidable Deaths

Avoidable deaths and admissions will be analysed across the conditions described in the table below.  A few conditions will also be analysed individually.

Table : Specific conditions for which admissions or deaths are considered avoidable. * denotes the condition will be analysed on its own. \* Denotes condition to be considered individual.

| Avoidable Deaths | Avoidable Admissions |
|------------------|----------------------|
| Acute Heart Failure\* | Acute Mental Crisis|
| Anaphalaxis | Angina|
| Asphyxiation | Blocked Urinary Catheter |
| Asthma | Cellulitis |
| Cardiac Arrest | Childhood Pyrexial |
| Falls in those <75 | Chronic Obstructive Pulmonary Disease |
| Fractured Neck of Femur | Deep Vein Thrombosis |
| Meningitis | Epileptic Seizure |
| Myocardial Infarction | Falls in those >75 |
| Non-superficial Head Injuries | Hypoglycaemia |
| Pregnancy and Birth Related Conditions | Non-specific Abdominal Pains |
| Road Traffic Accidents | Non-specific Chest Pains\* |
| Ruptured Aortic Aneurysm | Superficial Head Injuries |
| Self-harm | Urinary Tract Infections |
| Septic Shock | |
| Stroke/CVA\* | |


#### Steps

The closure of ED departments is modelled using a dummy variable (coded 0 for closed and 1 for open) to indicate whether the ED department is open/closed for any given month in a given hospital.  However, other factors might influence attendance and documentary analysis was undertaken at the case sites (where EDs closed) and one matched control for each case site to identify additional events that might impact on the indicators being considered.  These are detailed in full in [this spreadhsheet](https://goo.gl/TlhfCF) and  of the different steps identified they have been categorised into the introduction of the NHS111 Helpline (`nhs111`), other medical care centres opening (`other.centre`) and the diversion of ambulances (`ambulance.divert`) and are summarised in the table below for the ten hospitals.

Table: Steps used in the model. Dates indicate the month of event (relative month is shown in brackets).

Hospital         | ED closure      | NHS 111         | Other Centre    | Ambulance Diversion
-----------------|-----------------|-----------------|-----------------|---------------------
Bishop Auckland  | 2009-10-01 (25) | 2010-08-01 (35) |                 |
Whitehaven       |                 |                 |                 |
Hartlepool       | 2011-08-01 (25) | 2013-04-01 (45) | 2011-05-01 (22) |
Grimsby          |                 | 2010-11-01 (16) |                 |
Hemel Hempstead  | 2009-03-01 (25) |                 | 2008-10-01 (20) |
Warwick          |                 |                 |                 |
Newark           | 2011-04-01 (25) |                 |                 |
Southport        |                 | 2013-03-01 (48) | 2009-06-01 (03) |
Rochdale         | 2011-04-01 (25) | 2013-03-01 (48) |                 | 2010-08-01 (17)
Rotherham        |                 | 2013-03-01 (48) | 2009-06-01 (11) |

#### Panels

The panels that are being considered change depending on the type of anayses that are being performed (see above table).  If the summary data across a catchment area is being analysed under the 'step' models then the panels are the Trust/Hospital/Emergency Departments themselves.  If the data is being considered at the Lower Super Output Area (LSOA) as it is under the 'dose' models which include a 'change in ED time' term then the panels are the LSOAs themselves, since these are the units on which repeated measures over time are available and are being analysed.


#### Spurious Data Points

Two approaches are taken to identifying potentially spurious data points, the first is visual inspection of the raw data using time-series plots.  Potentially spruious data points will then be noted.  This method is however subjective and therefore subject to bias.  A more objective approach suggested was to the observations across all time points and calculate the mean and standard deviation  (`SD`) )and the identify any data points that are outside the range `mean -/+ A x SD`, where `A` is a pre-specified value, in this case `3`.  It was suggested that this method was applied to the methodologically similar analyses looking at [the effect of the introduction of NHS111](http://bmjopen.bmj.com/content/3/11/e003451.full)[@turner2013] but there is no mention of this aspect of data cleaning in the methods of the BMJ article, nor in the 210 page report submitted to funders.  This approach is not without its drawbacks as there are expected to be changes in the mean observed value pre/post intervention, so taking a global mean and the resulting high variance will potentially not exclude some possibly spurious data points.


#### Heteroskedasticity and Correlation

Because of the scope for [heterpskedasticity](https://en.wikipedia.org/wiki/Heteroscedasticity) (variable variance) between panels the study protool stated that results that were significant would be re-ananlysed using the square-root of the observed value to minimise variation rather than using approaches such as the[ARCH family of models](https://en.wikipedia.org/wiki/Autoregressive_conditional_heteroskedasticity).  However, the implementation of Prais-Winsten regression allows for different methods of estimating the variance.  Currently panel-corrected standard errors are used which are robust to heteroskedaasticity and contemporaneous correlation across panels, but other options are available, such as a Huber-White style sandwich estimateor for panel heteroskedasticity, panel weighted least squares procedure for heteroskedasticity or Parks-Kmenta FGLS to estimate both heteroskedasticity and correlation.  For full details see [Details under PanelAR](http://www.rdocumentation.org/packages/panelAR/functions/panelAR).


### Software

There are two packages for [R](https://www.r-projects.org/) that implement the Prais-Winsten method of adjusting for auto-correlation in time-series analyses, [panelAR](https://cran.r-project.org/web/packages/panelAR/index.html) or [prais](https://cran.r-project.org/web/packages/prais/index.html).  The panelAR package is being used for this work but it is intended to cross-validate these against the routines provided in [Stata (v14.1)](https://www.stata.com/) however the constarint of having to work with the data stored on a Virtual Machine (VM) this will only be possible for models which use ED panels as the observed counts of events at LSOA level mean the data would have potentially identifiable data which should remain on the VM.
