---
title: ClosED
output:
  html_document:
    theme: sandstone
    toc: false
    toc_float: false
    toc_depth: 5
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
##opts_chunk$set(dev = 'pdf')
opts_chunk$set(cache.path = 'cache/',
               width    = 200,
               fig.height = 8,
               fig.width  = 8)
## Set a seed
set.seed(69027181)
```
# {.tabset}

## Methods

```{r child = 'sections/methods.Rmd', eval = TRUE}
```

## Results {.tabset .tabset-fade}
```{r child = 'sections/results.Rmd', eval = TRUE}
```

<!--- Run all analyses --->
```{r child = 'sections/subsections/analysis.Rmd', eval = TRUE}
```

## Validation {.tabset .tabset-fade .tabset-pills}
```{r child = 'sections/validation.Rmd', eval = TRUE}
```
## Investigations {.tabset .tabset-fade .tabset-pills}
```{r child = 'sections/investigations.Rmd', eval = TRUE}
```

## ToDo {.tabset .tabset-fade .tabset-pills}
```{r child = 'sections/todo.Rmd', eval = TRUE}
```

## References

# References
