---
title: ClosED
output:
  html_document:
    theme: sandstone
    toc: false
    toc_float: false
    toc_depth: 5
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
##opts_chunk$set(dev = 'pdf')
opts_chunk$set(cache.path = 'cache/',
               width    = 200,
               fig.height = 8,
               fig.width  = 8)
## Set a seed
set.seed(69027181)
```
# {.tabset}

<!--- Run all analyses --->
```{r child = 'sections/subsections/negbin.Rmd', eval = TRUE}
```

## Model 1 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model1.Rmd', eval = TRUE}
```

## Model 2 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model2.Rmd', eval = TRUE}
```

## Model 3.1 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model3.1.Rmd', eval = TRUE}
```

## Model 3.2 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model3.2.Rmd', eval = TRUE}
```

## Model 4 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model4.Rmd', eval = TRUE}
```

## Model 5 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model5.Rmd', eval = TRUE}
```

## Model 6.1 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model6.1.Rmd', eval = TRUE}
```

## Model 6.2 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model6.2.Rmd', eval = TRUE}
```

## Model 7 {.tabset .tabset-fade}
```{r child = 'sections/negbin_model7.Rmd', eval = TRUE}
```
