#### Time-Series Plots

The number of attendances, by any mode (ambulance or otherwise) are plotted below (prior to the removal of potentially spurious data points).  The first figure shows all case sites for comparison, subsequent plots show a given case with its matched control sites.

##### Case Sites
```{r mode_of_arrival_any_time_series_plot_case, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
closed_ts_plot(df            = ed_attendances_by_mode_site_measure,
               indicator     = 'ed attendances',
               sub.indicator = 'any',
               steps         = TRUE,
               theme         = theme_bw(),
               tidy          = FALSE,
               facet         = FALSE,
               sites         = c('Bishop Auckland', 'Hartlepool', 'Hemel Hempstead', 'Newark', 'Rochdale'))
```

##### Bishop Auckland

```{r mode_of_arrival_any_time_series_plot_bishop, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
closed_ts_plot(df            = ed_attendances_by_mode_site_measure,
               indicator     = 'ed attendances',
               sub.indicator = 'any',
               steps         = TRUE,
               theme         = theme_bw(),
               tidy          = FALSE,
               facet         = FALSE,
               sites         = c('Bishop Auckland', 'Salford', 'Scarborough', 'Whitehaven'))
```

##### Hartlepool

```{r mode_of_arrival_any_time_series_plot_hartlepool, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
closed_ts_plot(df            = ed_attendances_by_mode_site_measure,
               indicator     = 'ed attendances',
               sub.indicator = 'any',
               steps         = TRUE,
               theme         = theme_bw(),
               tidy          = FALSE,
               facet         = FALSE,
               sites         = c('Hartlepool', 'Blackburn', 'Grimsby', 'Wigan'))
```

##### Hemel Hempstead

```{r mode_of_arrival_any_time_series_plot_hemel, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
closed_ts_plot(df            = ed_attendances_by_mode_site_measure,
               indicator     = 'ed attendances',
               sub.indicator = 'any',
               steps         = TRUE,
               theme         = theme_bw(),
               tidy          = FALSE,
               facet         = FALSE,
               sites         = c('Hemel Hempstead', 'Basingstoke', 'Warwick', 'Yeovil'))
```

##### Newark

```{r mode_of_arrival_any_time_series_plot_newark, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
closed_ts_plot(df            = ed_attendances_by_mode_site_measure,
               indicator     = 'ed attendances',
               sub.indicator = 'any',
               steps         = TRUE,
               theme         = theme_bw(),
               tidy          = FALSE,
               facet         = FALSE,
               sites         = c('Newark', 'Carlisle', 'Salisbury', 'Southport'))
```

##### Rochdale

```{r mode_of_arrival_any_time_series_plot_rochdale, echo = FALSE, cache = FALSE, results = 'hide', eval = TRUE}
closed_ts_plot(df            = ed_attendances_by_mode_site_measure,
               indicator     = 'ed attendances',
               sub.indicator = 'any',
               steps         = TRUE,
               theme         = theme_bw(),
               tidy          = FALSE,
               facet         = FALSE,
               sites         = c('Rochdale', 'Rotherham', 'Scunthorpe', 'Wansbeck'))
```

#### Model 1
