<!--- Runs all analyses, saving results as an R object for loading --->
<!--- Summary --->
```{r load_data, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
## Obtain the OS and node such that the data can be conditionally loaded
os <- .Platform$OS.type
node <- Sys.info()[['nodename']]
if(os != 'unix'){
    load('d:/Rpackages/rclosed/data/ed attendances by mode measure - lsoa - 2016-05-24 14.25.Rda')
    load('d:/Rpackages/rclosed/data/ed attendances by mode measure - site - 2016-05-24 14.26.Rda')
    load('d:/Rpackages/rclosed/data/unnecessary ed attendances measure - lsoa - 2016-05-24 14.26.Rda')
    load('d:/Rpackages/rclosed/data/unnecessary ed attendances measure - site - 2016-05-24 14.26.Rda')
    load('d:/Rpackages/rclosed/data/ed attendances admitted measure - lsoa - 2016-05-24 14.28.Rda')
    load('d:/Rpackages/rclosed/data/ed attendances admitted measure - site - 2016-05-24 14.28.Rda')
    load('d:/Rpackages/rclosed/data/emergency admissions measure - lsoa - 2016-05-24 14.30.Rda')
    load('d:/Rpackages/rclosed/data/emergency admissions measure - site - 2016-05-24 14.31.Rda')
##    load('d:/Rpackages/rclosed/data/critical care stays measure - lsoa - 2016-05-24 14.32.Rda')
##    load('d:/Rpackages/rclosed/data/critical care stays measure - site - 2016-05-24 14.32.Rda')
    load('d:/Rpackages/rclosed/data/critical care stays measure - lsoa - 2016-06-10 18.17.Rda')
    load('d:/Rpackages/rclosed/data/critical care stays measure - site - 2016-06-10 18.18.Rda')
    load('d:/Rpackages/rclosed/data/length of stay measure - lsoa - 2016-05-24 14.34.Rda')
    load('d:/Rpackages/rclosed/data/length of stay measure - site - 2016-05-24 14.35.Rda')
    load('d:/Rpackages/rclosed/data/ambulance mean times measure - lsoa - 2016-06-17 01.21.Rda')
    load('d:/Rpackages/rclosed/data/ambulance mean times measure - site - 2016-06-17 01.23.Rda')
    load('d:/Rpackages/rclosed/data/case fatality measure - lsoa - 2016-06-10 18.09.Rda')
    load('d:/Rpackages/rclosed/data/case fatality measure - site - 2016-06-10 18.10.Rda')
} else if(os == 'unix' & node == 'mcru-closed-hp.shef.ac.uk'){
    load('~/work/closed/lib/data/ed attendances by mode measure - lsoa - 2016-05-24 14.25.Rda')
    load('~/work/closed/lib/data/ed attendances by mode measure - site - 2016-05-24 14.26.Rda')
    load('~/work/closed/lib/data/unnecessary ed attendances measure - lsoa - 2016-05-24 14.26.Rda')
    load('~/work/closed/lib/data/unnecessary ed attendances measure - site - 2016-05-24 14.26.Rda')
    load('~/work/closed/lib/data/ed attendances admitted measure - lsoa - 2016-05-24 14.28.Rda')
    load('~/work/closed/lib/data/ed attendances admitted measure - site - 2016-05-24 14.28.Rda')
    load('~/work/closed/lib/data/emergency admissions measure - lsoa - 2016-05-24 14.30.Rda')
    load('~/work/closed/lib/data/emergency admissions measure - site - 2016-05-24 14.31.Rda')
    ## load('~/work/closed/lib/data/critical care stays measure - lsoa - 2016-05-24 14.32.Rda')
    ## load('~/work/closed/lib/data/critical care stays measure - site - 2016-05-24 14.32.Rda')
    load('~/work/closed/lib/data/critical care stays measure - lsoa - 2016-06-10 18.17.Rda')
    load('~/work/closed/lib/data/critical care stays measure - site - 2016-06-10 18.18.Rda')
    load('~/work/closed/lib/data/length of stay measure - lsoa - 2016-05-24 14.34.Rda')
    load('~/work/closed/lib/data/length of stay measure - site - 2016-05-24 14.35.Rda')
    load('~/work/closed/lib/data/ambulance mean times measure - lsoa - 2016-06-17 01.21.Rda')
    load('~/work/closed/lib/data/ambulance mean times measure - site - 2016-06-17 01.23.Rda')
    load('~/work/closed/lib/data/case fatality measure - lsoa - 2016-06-10 18.09.Rda')
    load('~/work/closed/lib/data/case fatality measure - site - 2016-06-10 18.10.Rda')
}
```
```{r define_models, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
## Set model options here (easier when tweaking en-mass)
model.opts <- list()
model.opts
model.opts$mod1 <- c('closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod2 <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod3 <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod4 <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod5 <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert')
model.opts$mod6 <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert', 'diff.time.to.ed')
if(os != 'unix' | node != 'mcru-closed-hp.shef.ac.uk'){
    model.opts$mod7 = NULL
} else{
    model.opts$mod7 <- c('town * closure', 'season', 'relative.month', 'nhs111', 'other.centre', 'ambulance.divert', 'diff.time.to.ed')
}
model.opts$panel.lsoa		<- 'lsoa'
model.opts$panel.trust		<- 'town'
model.opts$timevar		<- 'relative.month'
model.opts$outcome		<- 'value'
model.opts$autocorr		<- 'ar1'
model.opts$panelcorrmethod	<- 'pcse'
model.opts$coefficients		<- 'closure.town'
model.opts$seq.times		<- FALSE
model.opts$plot			<- TRUE
model.opts$common.y		<- TRUE
model.opts$theme		<- theme_bw()
model.opts$return.df		<- FALSE
model.opts$return.model		<- TRUE
model.opts$return.residuals	<- TRUE
model.opts$join.line            <- FALSE
model.opts$legend               <- TRUE
model.opts$rho.na.rm            <- TRUE
```
```{r summary_analysis, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
## Summarise differences in time to ED
diff.time.to.ed <- closed_summary(df          = ed_attendances_by_mode_measure,
                             df.steps    = sites,
                             vars        = value,
                             digits      = 3,
                             latex       = FALSE,
                             html        = FALSE)
## Simple summary of the missing data across datasets
check.ed.attendances <- closed_missing_summary(df.lsoa = ed_attendances_by_mode_measure,
                                               df.site = ed_attendances_by_mode_site_measure)
check.ed.unnecessary <- closed_missing_summary(df.lsoa = unnecessary_ed_attendances_measure,
                                               df.site = unnecessary_ed_attendances_site_measure)
check.ed.admitted    <- closed_missing_summary(df.lsoa = ed_attendances_admitted_measure,
                                               df.site = ed_attendances_admitted_site_measure)
check.critical.care  <- closed_missing_summary(df.lsoa = critical_care_cips_measure,
                                               df.site = critical_care_cips_site_measure)
check.length.stay    <- closed_missing_summary(df.lsoa = length_of_stay_measure,
                                               df.site = length_of_stay_site_measure)
## Bind into two data frames for tabulating
check.length.stay$check.lsoa$sub_measure[is.na(check.length.stay$check.lsoa$sub_measure)] <- "N/A"
check.lsoa <- rbind(check.ed.attendances$check.lsoa,
                    check.ed.unnecessary$.lsoa,
                    check.ed.admitted$check.lsoa,
                    check.critical.care$check.lsoa,
                    check.length.stay$check.lsoa) %>%
              ungroup() %>%
              arrange(measure, sub_measure, relative_month, group, town) %>%
	      dplyr::select(measure, sub_measure, town, relative_month, n)
names(check.lsoa) <- c('Measure', 'Sub-Measure', 'Town', 'Relative Month', 'LSOAs')

check.length.stay$check.site$sub_measure[is.na(check.length.stay$check.site$sub_measure)] <- "N/A"
check.site <- rbind(check.ed.attendances$check.site,
                    check.ed.unnecessary$.site,
                    check.ed.admitted$check.site,
                    check.critical.care$check.site,
                    check.length.stay$check.site) %>%
              arrange(measure, sub_measure, relative_month, group, town) %>%
	      dplyr::select(measure, sub_measure, town, relative_month)
names(check.site) <- c('Measure', 'Sub-Measure', 'Town', 'Relative Month')
```
<!--- Mode of Arrival --->
```{r mode_of_arrival_any, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
mode.of.arrival.any <- closed_models(df.lsoa          = ed_attendances_by_mode_measure,
                                     df.trust         = ed_attendances_by_mode_site_measure,
                                     indicator        = 'ed attendances',
                                     sub.indicator    = 'any',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3           = model.opts$mod3,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     ## return.df        = model.opts$return.df,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
				     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
<!--- All Emergency Admissions - Any --->
```{r all_emergency_admissions_all, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
all.emergency.admissions.all <- closed_models(df.lsoa         = emergency_admissions_measure,
                                     df.trust         = emergency_admissions_site_measure,
                                     indicator        = 'all emergency admissions',
                                     sub.indicator    = 'all',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3           = model.opts$mod3,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
				     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```
<!--- Case Fatality Ratio --->
```{r case_fatality_ratio, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
case.fatality.ratio.any <- closed_models(df.lsoa         = case_fatality_measure,
                                     df.trust         = case_fatality_site_measure,
                                     indicator        = 'case fatality ratio',
                                     sub.indicator    = 'any',
                                     steps            = c('closure'),
                                     fit.with         = model.opts$fit.with,
                                     panel.lsoa       = model.opts$panel.lsoa,
                                     panel.trust      = model.opts$panel.trust,
                                     timevar          = model.opts$timevar,
                                     outcome          = model.opts$outcome,
                                     model1           = model.opts$mod1,
                                     model2           = model.opts$mod2,
                                     model3           = model.opts$mod3,
                                     model4           = model.opts$mod4,
                                     model5           = model.opts$mod5,
                                     model6           = model.opts$mod6,
                                     model7           = model.opts$mod7,
                                     autocorr         = model.opts$autocorr,
                                     panelcorrmethod  = model.opts$panelcorrmethod,
                                     coefficients     = model.opts$coefficients,
                                     seq.times        = model.opts$seq.times,
                                     rho.na.rm        = TRUE,
                                     plot             = model.opts$plot,
                                     common.y         = model.opts$common.y,
                                     theme            = model.opts$theme,
                                     return.df        = model.opts$return.df,
                                     return.model     = model.opts$return.model,
				     return.residuals = model.opts$return.residuals,
                                     join.line        = model.opts$join.line,
                                     legend           = model.opts$legend)
```

<!--- Ambulance Mean Times - Call to Destination --->
```{r ambulance_mean_times_call_to_dest, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
## ambulance.mean.times.call.to.dest <- closed_models(df.lsoa         = amb_mean_times_measure,
##                                      df.trust         = amb_mean_times_site_measure,
##                                      indicator        = 'ambulance mean times',
##                                      sub.indicator    = 'call_to_dest',
##                                      steps            = c('closure'),
##                                      fit.with         = model.opts$fit.with,
##                                      panel.lsoa       = model.opts$panel.lsoa,
##                                      panel.trust      = model.opts$panel.trust,
##                                      timevar          = model.opts$timevar,
##                                      outcome          = model.opts$outcome,
##                                      model1           = model.opts$mod1,
##                                      model2           = model.opts$mod2,
##                                      model3           = model.opts$mod3,
##                                      model4           = model.opts$mod4,
##                                      model5           = model.opts$mod5,
##                                      model6           = model.opts$mod6,
##                                      model7           = model.opts$mod7,
##                                      autocorr         = model.opts$autocorr,
##                                      panelcorrmethod  = model.opts$panelcorrmethod,
##                                      coefficients     = model.opts$coefficients,
##                                      seq.times        = model.opts$seq.times,
##                                      plot             = model.opts$plot,
##                                      common.y         = model.opts$common.y,
##                                      theme            = model.opts$theme,
##                                      return.df        = model.opts$return.df,
##                                      return.model     = model.opts$return.model,
## 				     return.residuals = model.opts$return.residuals,
##                                      join.line        = model.opts$join.line,
##                                      legend           = model.opts$legend)
## Alternatively run everything outside of the function since its not set up to deal with partial data sets.
## Sort data out (conversion, steps etc.)
## Names/data frame/filtering
names(amb_mean_times_measure) <- gsub("_", ".", names(amb_mean_times_measure))
amb_mean_times_measure <- as.data.frame(amb_mean_times_measure) %>%
    dplyr::filter(measure == 'ambulance mean times' & sub.measure == 'call_to_dest')
amb_mean_times_measure$town <- factor(amb_mean_times_measure$town)
## Add Season
amb_mean_times_measure$season <- 1
amb_mean_times_measure <- within(amb_mean_times_measure, {
                                 season[month(yearmonth) == 1  | month(yearmonth) == 2]  <- 1
                                 season[month(yearmonth) == 3  | month(yearmonth) == 4]  <- 2
                                 season[month(yearmonth) == 5  | month(yearmonth) == 6]  <- 3
                                 season[month(yearmonth) == 7  | month(yearmonth) == 8]  <- 4
                                 season[month(yearmonth) == 9  | month(yearmonth) == 10] <- 5
                                 season[month(yearmonth) == 11 | month(yearmonth) == 12] <- 6
})
## Dummy steps
amb_mean_times_measure$closure  <- ifelse(amb_mean_times_measure$relative.month  > 24, 1, 0)
amb_mean_times_measure <- mutate(amb_mean_times_measure,
                                 nhs111 = ifelse((town == 'Bishop Auckland' & relative.month >= 35) |
                                                 (town == 'Southport' & relative.month >= 48) |
                                                 ## ToDo - Uncomment once confirmed and revised dates available
                                                 (town == 'Rochdale' & relative.month >= 48) |
                                                 (town == 'Rotherham' & relative.month >= 48) |
                                                 (town == 'Hartlepool' & relative.month >= 45) |
                                                 (town == 'Grimsby' & relative.month >= 16),
                                                 1, 0),
                                 ambulance.divert = ifelse(town == 'Rochdale' & relative.month >= 17, 1, 0),
                                 other.centre = ifelse((town == 'Hemel Hempstead' & relative.month >= 20) |
                                                       (town == 'Newark' & relative.month >= 3) |
                                                       (town == 'Rochdale' & relative.month >= 11) |
                                                       (town == 'Hartlepool' & relative.month >= 22),
                                                       1, 0)
                                 )
## Repeat all for Site data frame
names(amb_mean_times_site_measure) <- gsub("_", ".", names(amb_mean_times_site_measure))
amb_mean_times_site_measure <- as.data.frame(amb_mean_times_site_measure) %>%
    dplyr::filter(measure == 'ambulance mean times' & sub.measure == 'call_to_dest')
amb_mean_times_site_measure$town <- factor(amb_mean_times_site_measure$town)
amb_mean_times_site_measure$season <- 1
amb_mean_times_site_measure <- within(amb_mean_times_site_measure, {
                                 season[month(yearmonth) == 1  | month(yearmonth) == 2]  <- 1
                                 season[month(yearmonth) == 3  | month(yearmonth) == 4]  <- 2
                                 season[month(yearmonth) == 5  | month(yearmonth) == 6]  <- 3
                                 season[month(yearmonth) == 7  | month(yearmonth) == 8]  <- 4
                                 season[month(yearmonth) == 9  | month(yearmonth) == 10] <- 5
                                 season[month(yearmonth) == 11 | month(yearmonth) == 12] <- 6
})
amb_mean_times_site_measure$closure  <- ifelse(amb_mean_times_site_measure$relative.month  > 24, 1, 0)
amb_mean_times_site_measure <- mutate(amb_mean_times_site_measure,
                                     nhs111 = ifelse((town == 'Bishop Auckland' & relative.month >= 35) |
                                                     (town == 'Southport' & relative.month >= 48) |
                                                     ## ToDo - Uncomment once confirmed and revised dates available
                                                     (town == 'Rochdale' & relative.month >= 48) |
                                                     (town == 'Rotherham' & relative.month >= 48) |
                                                     (town == 'Hartlepool' & relative.month >= 45) |
                                                     (town == 'Grimsby' & relative.month >= 16),
                                                     1, 0),
                                     ambulance.divert = ifelse(town == 'Rochdale' & relative.month >= 17, 1, 0),
                                     other.centre = ifelse((town == 'Hemel Hempstead' & relative.month >= 20) |
                                                           (town == 'Newark' & relative.month >= 3) |
                                                           (town == 'Rochdale' & relative.month >= 11) |
                                                           (town == 'Hartlepool' & relative.month >= 22),
                                                           1, 0)
                                     )
## Model 1
formula.model1 <- reformulate(response = 'value',
                              termlabels = model.opts$mod1)
sites <-c('Hartlepool')
model1.panelar.hartlepool <- filter(amb_mean_times_site_measure,
                                    town == 'Hartlepool') %>%
                             panelAR(formula         = formula.model1,
                                     timeVar         = model.opts$timevar,
                                     panelVar        = model.opts$panel.trust,
                                     autoCorr        = model.opts$autocorr,
                                     panelCorrMethod = 'pcse',
                                     seq.times       = model.opts$seq.times,
                                     rho.na.rm       = model.opts$rho.na.rm)
## Model 2
formula.model2 <- reformulate(response = 'value',
                              termlabels = model.opts$mod2)
amb_mean_times_site_measure$town <- relevel(amb_mean_times_site_measure$town, ref = 'Grimsby')
model2.panelar.hartlepool <- filter(amb_mean_times_site_measure,
                                    town == 'Hartlepool' | town == 'Grimsby') %>%
                             panelAR(formula         = formula.model2,
                                     timeVar         = model.opts$timevar,
                                     panelVar        = model.opts$panel.trust,
                                     autoCorr        = model.opts$autocorr,
                                     panelCorrMethod = 'pcse',
                                     seq.times       = model.opts$seq.times,
                                     rho.na.rm       = model.opts$rho.na.rm)
## Model 6
## formula.model6 <- reformulate(response = 'value',
##                               termlabels = model.opts$mod6)
## amb_mean_times_measure$town <- relevel(amb_mean_times_measure$town, ref = 'Grimsby')
## model6.panelar.hartlepool <- filter(amb_mean_times_measure,
##                                     town == 'Hartlepool' | town == 'Grimsby') %>%
##                              panelAR(formula         = formula.model6,
##                                      timeVar         = model.opts$timevar,
##                                      panelVar        = model.opts$panel.lsoa,
##                                      autoCorr        = model.opts$autocorr,
##                                      panelCorrMethod = 'pcse',
##                                      seq.times       = model.opts$seq.times,
##                                      rho.na.rm       = model.opts$rho.na.rm)
## Extract and Combine coefficients
extract_coefficients <- function(x,
                                 .site          = 'Hartlepool',
                                 .indicator     = 'ambulance mean times',
                                 .sub.indicator = 'call_to_dest'){
    ## Extract coefficients from a given model
    coefficients <- summary(x) %>%
        coef() %>%
        as.data.frame()
    coefficients$term <- rownames(coefficients)
    rownames(coefficients) <- NULL
    coefficients$site          <- .site
    coefficients$indicator     <- .indicator
    coefficients$sub.indicator <- .sub.indicator
    coefficients$r2            <- x$r2
    return(coefficients)
}
model1.panelar.hartlepool.coeff <- extract_coefficients(model1.panelar.hartlepool)
model1.panelar.hartlepool.r2    <- model1.panelar.hartlepool$r2
model2.panelar.hartlepool.coeff <- extract_coefficients(model2.panelar.hartlepool)
model2.panelar.hartlepool.r2    <- model2.panelar.hartlepool$r2
rm(extract_coefficients)
```

<!--- Save Results --->
```{r save_results, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
save(model.opts,
     diff.time.to.ed,
     check.site,
     mode.of.arrival.any,
     avoidable.emergency.admissions.any,
     case.fatality.ratio.any,
     model1.panelar.hartlepool,
     model1.panelar.hartlepool.coeff,
     model1.panelar.hartlepool.r2,
     model2.panelar.hartlepool,
     model2.panelar.hartlepool.coeff,
     model2.panelar.hartlepool.r2,
     file = '~/work/closed/knitr/pag_20160704/results.RData')
```
<!--- Load Results --->
```{r load_results, echo = FALSE, cache = FALSE, results = 'hide', message = FALSE, eval = TRUE}
load(file = '~/work/closed/knitr/pag_20160704/results.RData')
```
